### ISSUE TITLE
debug and display always call display

### ISSUE THREAD

**Issue by Silentdoer** [dtolnay/anyhow#101]
like println!("{}, {:?}", err, err) always call err Display

**Comment by hbina** [comment]
This can't be right..I think the relevant code here https://github.com/dtolnay/anyhow/blob/7954754d2084b7d9e3f45ea7289d8d8332260fb0/src/error.rs#L488-L511

Do you have some code to produce this issue?

**Comment by dtolnay** [comment]
This is the intended behavior. https://docs.rs/anyhow/1.0.54/anyhow/struct.Error.html#display-representations describes how `{}` and `{:?}` are treated, along with the other format specifiers `{:#}` and `{:#?}`.
