### ISSUE TITLE
question: is `anyhow::Error/Result` a proper choice for method signatures of the library API (as opposed to internal use in the final application) ?

### ISSUE THREAD

**Issue by yskopets** [dtolnay/anyhow#102]
The library description says that `anyhow::Error` is intended for use **in Rust applications**.

> This library provides anyhow::Error, a trait object based error type for easy idiomatic error handling **in Rust applications**.

And [dependant library crates](https://crates.io/crates/anyhow/reverse_dependencies) are mostly using `anyhow` as their `dev-dependency` (so that it only appears in `main()` function of their examples).

Could you please advise if `anyhow` would be a proper choice for method signatures of the library API ?

For a better context:
* my library expects its users to implement a trait object
* every operation of the trait object can return an error
* I was trying to avoid putting constraints on what errors users might return, so the concrete `Error` type right now is `Box<Error>`

I've received feedback that `Box<Error>` is not good enough.

I was considering `anyhow` at some point. But then I was pointed to [eyre](https://github.com/yaahc/eyre) (a fork of `anyhow`).

Now I'm lost.

* Does it make sense for a library to make `anyhow` or `eyre` a part of its API ?
* Or should a library stay away from this  choice ?
* Would it be a good idea to use `Box<Error>` in the API and let users to choose `anyhow`, `eyre`, etc ?

Thanks in advance!

**Comment by F0Xde** [comment]
For errors returned by a trait you could use an associated `Error` type, not sure what else you need to do with these errors.

**Comment by dtolnay** [comment]
Per the part of the readme that you quoted, the use case that you've described is not one of the intended uses of this library.
