### ISSUE TITLE
Document usage with Rocket

### ISSUE THREAD

**Issue by arturh85** [dtolnay/anyhow#105]
When using anyhow together with Rocket you get the following error:

```
 the trait `rocket::response::Responder<'_, '_>` is not implemented for `anyhow::Error`
```

This is related to: https://github.com/SergioBenitez/Rocket/issues/856 and can be fixed by wrapping the error type with rocket::response::Debug:

```
#[get("/foo")]
pub fn foo() -> Result<i32, rocket::response::Debug<anyhow::Error>> {
    Ok(1)
}
```

Due to the popularity of rocket my guess is that many people may stumble opon this issue, so I would suggest documenting it in the README.

**Comment by dtolnay** [comment]
I think I would prefer not to add Rocket-specific documentation in this crate. If I got that error message, the place I would think to look is the documentation of rocket::response::Responder.

**Comment by Piping** [comment]
How about a section of document for integrating with other popular framework/libraries?

**Comment by mimoo** [comment]
I'd suggest that this should live on rocket's doc, not anyhow's doc

**Comment by mkoval** [comment]
Wrapping `anyhow::Error` with `rocket::response::Debug` doesn't fix the issue on the example code posted above. I get this compile error with Anyhow 1.0.38 and Rocket 0.4.6:
```
error[E0277]: the trait bound `std::result::Result<i32, rocket::response::Debug<anyhow::Error>>: Responder<'_>` is not satisfied
   --> src/main.rs:44:15
    |
44  | fn index() -> Result<i32, rocket::response::Debug<anyhow::Error>> {
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Responder<'_>` is not implemented for `std::result::Result<i32, rocket::response::Debug<anyhow::Error>>`
    |
   ::: /Users/mkoval/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.6/src/handler.rs:202:20
    |
202 |     pub fn from<T: Responder<'r>>(req: &Request, responder: T) -> Outcome<'r> {
    |                    ------------- required by this bound in `handler::<impl rocket::Outcome<rocket::Response<'r>, rocket::http::Status, rocket::Data>>::from`
    |
    = help: the following implementations were found:
              <std::result::Result<R, E> as Responder<'r>>
              <std::result::Result<R, E> as Responder<'r>>
```

I'm not sure how to debug this. It looks like it there are two different implementations of Responder for the generic `Result<R, E>` type, neither is applicable here. How is that possible? Are some type bounds omitted?
