### ISSUE TITLE
Proposal: An ErrorProxy trait for libraries that wish to generically consume errors

### ISSUE THREAD

**Issue by D1plo1d** [dtolnay/anyhow#110]
## Strawman Proposal

Create a minimal `ErrorPoxy` trait in a new crate and add an implementation to anyhow (and similar error aggregation libraries) so that libraries that wish to generically consume errors can access backtraces and error sources for types such as `anyhow::Error` that cannot implement `std::error::Error`.

## Background
Due to cohesion limitations anyhow::Error cannot implement std::error::Error without creating an infinite `impl From<anyhow::Error> for anyhow::Error` loop.

Crates such as [async-graphql](https://github.com/async-graphql/async-graphql) and [sled](https://github.com/spacejam/sled) consume user-defined error types and would benefit from a Trait that provided source and backtrace information across the most common error-like types.

In order to consume an error crates have three options at the moment:

1. Drop Anyhow support and only accept types that implement `std::error::Errors`.
2. Treat all errors as `fmt::Display + fmt::Debug` dropping error chaining and backtrace information
3. Choose one error handling library and force all users to use it - eg, async-graphql could choose to depend on error-chain or anyhow but not both (a feature flag could toggle this but then libraries built on async-graphql have the same problem).

Note: This trait would need to be implemented inside anyhow (and similarly error-chain, etc.) because an external implementation leads to a conflicting implementation compiler error since anyhow the compiler cannot guarentee that future versions of anyhow won't implement std::error::Error.

## Example Implementation
```rust
use std::error::Error;
use error_proxy::ErrorProxy;

#[cfg(backtrace)]
use crate::backtrace::Backtrace;

impl ErrorProxy for anyhow::Error {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        <self as anyhow::Error>.source()
    }

    #[cfg(backtrace)]
    fn backtrace(&self) -> Option<&Backtrace> {
        <self as anyhow::Error>::backtrace(self)
    }
}
```

Edit: Created a crate for this: https://crates.io/crates/error-proxy

**Comment by dtolnay** [comment]
I would prefer if this were done externally, i.e. putting the following impl in whatever crate defines ErrorProxy.

```rust
#[cfg(feature = "anyhow")]
impl ErrorProxy for anyhow::Error {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        (**self).source()
    }
    fn backtrace(&self) -> Option<&Backtrace> {
        Some(anyhow::Error::backtrace(self))
    }
}
```

**Comment by D1plo1d** [comment]
@dtolnay Appreciate you looking into this. Problem there is AFAIK we end up with a compiler error if we also include:
```
impl ErrorProxy for dyn std::error::Error + 'static {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        Some(self)
    }

    #[cfg(backtrace)]
    fn backtrace(&self) -> Option<&Backtrace> {
        std::error::Error::backtrace(self)
    }
}
```
As I understand it the issue is that the compiler can't guarantee that a future version of Anyhow won't implement std::error::Error. I think the idea is that adding traits should never be a breaking change but I could be wrong.

**Comment by dtolnay** [comment]
It compiles fine though.

```rust
#![feature(backtrace)]
use std::backtrace::Backtrace;
use std::error::Error;

pub trait ErrorProxy {
    fn source(&self) -> Option<&(dyn Error + 'static)>;
    fn backtrace(&self) -> Option<&Backtrace>;
}

impl ErrorProxy for dyn std::error::Error {
    fn source(&self) -> Option<&(dyn Error + 'static)> { unimplemented!() }
    fn backtrace(&self) -> Option<&Backtrace> { unimplemented!() }
}

impl ErrorProxy for anyhow::Error {
    fn source(&self) -> Option<&(dyn Error + 'static)> { unimplemented!() }
    fn backtrace(&self) -> Option<&Backtrace> { unimplemented!() }
}
```

**Comment by dtolnay** [comment]
I'll close the issue since I don't intend to introduce a dependency for this. Thanks anyway!

**Comment by D1plo1d** [comment]
Oh weird, I was sure that would error. Ok, I'll give it a shot. Generally does a trait sound like a good approach for libraries?

**Comment by jfirebaugh** [comment]
So how do you actually define a method that uses `ErrorProxy` to generically consume errors? My attempts end up with "trait bound  is not satisfied" errors when passing errors that impl `std::error::Error`:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=4e68530294ba1ebc806e6eca2766c377
