### ISSUE TITLE
`ensure!` does not call `from`

### ISSUE THREAD

**Issue by leoyvens** [dtolnay/anyhow#112]
I don't know if this is a bug or a docs problem, but the docs say:
```
This macro is equivalent to `return Err(From::from($err))`.
```

But that is not the case as this example shows:

```
#[derive(Debug)]
struct MyError(anyhow::Error);

impl From<anyhow::Error> for MyError {
    fn from(e: anyhow::Error) -> Self {
        MyError(e)
    }
}

fn main() -> Result<(), MyError> {
    anyhow::ensure!(false, anyhow::anyhow!("foo"));
    Ok(())
}
```

**Comment by MarijnS95** [comment]
We're running into the same issue with `thiserror` and the `#[from]` macro:

```rust
use thiserror::Error;

#[derive(Error, Debug)]
pub enum MyError {
    #[error(transparent)]
    Anyhow(#[from] anyhow::Error),
}

#[test]
fn main() -> Result<(), MyError> {
    anyhow::ensure!(false, "foo");
    // return Err(anyhow::anyhow!("foo").into());
    Ok(())
}
```

Effectively `bail` nor `ensure` call `.into()`, requiring us to manually write the commented `return` statement with a `.into()` instead.

Simply adding `.into()` to the macros solves both cases but breaks unit tests in `test_macros.rs` as the return type of the closures can't be derived anymore.

@dtolnay Do you happen to know of a way to support these cases without breaking the expected implicit `anyhow::Error` return type of these macros? Right now we're not able to use them in conjunction with `thiserror` unless coming up with our own `ensure_into`/`bail_into` variants.

**Comment by dtolnay** [comment]
This was a documentation bug, as the current behavior of the macros is intended. I don't know of a way to support a range of error return types without leading to more type inference failures involving closures, which I consider worse. :slightly_frowning_face:

**Comment by MarijnS95** [comment]
@dtolnay Thanks for clearing up the docs! We figured as much (it's anyway a breaking API change) and will have to roll our own macros that take care of `.into()`, unless you feel that's worth pulling into `anyhow` as `bail_into` and `ensure_into`?

**Comment by leoyvens** [comment]
I've also rolled my own macro, it would be nice to have this functionality in `anyhow`, even if separate.

**Comment by dtolnay** [comment]
I think I would prefer not to build this into this crate. The use cases that anyhow is intended for involve application code in which almost every Result return uses anyhow::Error, so for the small remainder of functions it's reasonable to write a `return` -- or create a custom macro downstream if the codebase's idioms are somewhat different (as `bail!`/`ensure!` are quite simple macros).

**Comment by dtolnay** [comment]
For anyone landing here from search needing something to copy:

```rust
macro_rules! bail {
    ($($err:tt)*) => {
        return Err(anyhow::anyhow!($($err)*).into());
    };
}
```

```rust
macro_rules! ensure {
    ($cond:expr, $($err:tt)*) => {
        if !$cond {
            return Err(anyhow::anyhow!($($err)*).into());
        }
    };
}
```
