### ISSUE TITLE
Add trait for Option<T> that converts to Result<T, anyhow::Error> with "NoneError"

### ISSUE THREAD

**Issue by trevyn** [dtolnay/anyhow#116]
Something along the lines of:

```
trait Ok<T> {
 fn ok(self) -> Result<T, anyhow::Error>;
}

impl<T> Ok<T> for Option<T> {
 fn ok(self) -> Result<T, anyhow::Error> {
  self.ok_or_else(|| anyhow::anyhow!("NoneError"))
 }
}
```

**Comment by Boscop** [comment]
Yes please! I have MANY instances of this pattern in my code. But with a descriptive message each time.
So please add a convenience method that does this:
```rust
opt.ok_or_else(|| anyhow!(<fmt_args>))
```
Such that `fmt_args` can still be specified. It can't be done with a normal method but with a macro:
```rust
let x: T = unwropt!(opt, "foo {}", 42)?;
```
But the most economic would be a [postfix macro](https://github.com/est31/postfix-macros), which is possible on stable Rust :)

**Comment by dtolnay** [comment]
Conversion from `Option<T>` to `Result<T, anyhow::Error>` is supported by the [Context](https://docs.rs/anyhow/1.0.34/anyhow/trait.Context.html) trait already. You can provide a meaningful message beyond NoneError.

```rust
use anyhow::{Context, Result};

fn f() -> Option<()> {
    None
}

fn main() -> Result<()> {
    let _ = f().context("NoneError")?;
    Ok(())
}
```
