### ISSUE TITLE
How reliable is the Debug implementation of anyhow::Error?

### ISSUE THREAD

**Issue by stevenroose** [dtolnay/anyhow#119]
I really like the way the Debug implementation iterates the causes etc. However, I think it's generally good practice to not rely on fmt::Debug implementations for user output as I generally think fmt::Debug, as opposed to Display, has a more loose contract.

> Debug should format the output in a programmer-facing, debugging context.

vs

> Display is similar to Debug, but Display is for user-facing output, and so cannot be derived.

So it'd be great if there was a way to access the current-Debug formatting somehow in a way that is more dedicated to stay available. If you believe that's not the purpose of this crate, I would probably agree/accept that.

**Comment by BurntSushi** [comment]
As the docs say:

> The Debug format “{:?}” includes your backtrace if one was captured. Note that this is the representation you get by default if you return an error from fn main instead of printing it explicitly yourself.

The second sentence is key here, and is presumably why Debug output does not look like traditional debug output. It is the way it is so that `fn main() -> anyhow::Result<()> { ... }` works how most would hope it to.

If you need conventional debug output, then again, as the docs say:

> To see a conventional struct-style Debug representation, use “{:#?}”.

**Comment by dtolnay** [comment]
> it'd be great if there was a way to access the current-Debug formatting somehow in a way that is more dedicated to stay available.

I don't think there is another API that I would want to expose in this crate. If you need a representation that is permanent, you can iterate the cause chain yourself and format it all in exactly the representation that you want to set in stone forever. For example the following in `cargo`: https://github.com/rust-lang/cargo/blob/46c9b51957e335ad03051ae8c513f3ba2a55b3b2/src/cargo/lib.rs#L78-L106
