### ISSUE TITLE
`impl Context for Result<T, ()>`

### ISSUE THREAD

**Issue by jamadazi** [dtolnay/anyhow#122]
Some libraries have functions that return `Result`s with `()` as the `Err` type. Since `()` does not impl `std::error::Error`, `anyhow` has trouble handling it.

I want to be able to call `.context()?` on it, so I can easily return an error from my function. I can already do this with `Option<T>`, as `Context` is implemented for it, so not supporting it for `Result<T, ()>` feels like an omission to me.

**Comment by jamadazi** [comment]
Just after posting this, I realised that I can trivially work around this by calling `.ok()` to turn the `Result<T, ()>` into an `Option<T>`. Just `.ok().context(...)?;` :smile: 

I still think it would be nice if this was supported directly, so I am going to leave this issue open.

**Comment by dtolnay** [comment]
I think I would prefer not to add this, but if it comes up often in your codebase then you could add an extension trait in your own crate:

```rust
use anyhow::{Error, Result};
use std::fmt::{Debug, Display};

trait VoidContext<T> {
    fn context(self, context: impl Debug + Display + Send + Sync + 'static) -> Result<T>;
}

impl<T> VoidContext<T> for Result<T, ()> {
    fn context(self, context: impl Debug + Display + Send + Sync + 'static) -> Result<T> {
        self.map_err(|()| Error::msg(context))
    }
}
```
