### ISSUE TITLE
Function-attribute to wrap function's returned Result with context containing function name?

### ISSUE THREAD

**Issue by Boscop** [dtolnay/anyhow#124]
Is there a way to remove the boilerplate when I always want to have the function name (and args) as context with anyhow?
So that I don't have to write every function like this:
```rust
fn function_name(arg: A) -> Result<R> {
    (try {
        // ...
    }: Result<R>).with_context(|| format!("function_name({:?})", arg))
}
```
Maybe with a `#[func_context(args = true)]` attribute?

It would be more readable than a stacktrace and also contain args.

**Comment by dtolnay** [comment]
https://github.com/yoshuawuyts/context-attribute does something like this.
