### ISSUE TITLE
`ensure!()` doesn't work in `try` blocks because it calls `return`

### ISSUE THREAD

**Issue by Boscop** [dtolnay/anyhow#125]
`ensure!()` doesn't work in `try` blocks [because it calls `return`](https://docs.rs/anyhow/1.0.34/src/anyhow/macros.rs.html#115-131):

![image](https://user-images.githubusercontent.com/535593/99144441-36a16a80-2666-11eb-8bdf-89c5b6c8a7fb.png)

Could you please fix it by writing
```rust
$crate::private::Err($crate::anyhow!($msg))?;
```
instead of `return`? :)

**Comment by Boscop** [comment]
Similarly with `bail!()`.

**Comment by dtolnay** [comment]
This is intentional, but you don't need to use the builtin `ensure` macro. You could add this in your crate to get that behavior:

```rust
macro_rules! ensure {
    ($cond:expr, $($msg:tt)*) => {
        if !$cond { Err(anyhow::anyhow!($($msg)*))?; }
    };
}
```

**Comment by Boscop** [comment]
@dtolnay Hm, what is the reasoning behind this intention? 
It's quite surprising (from a UX perspective) to users that it doesn't work in `try {}` blocks.

Could you please add a 2nd macro to this crate then, which works in `try {}`? :)
I'm sure many other users of this crate would want `ensure` & `bail` to work in `try` blocks.
