### ISSUE TITLE
Attribute proc-macro to wrap function return type `T` in `anyhow::Result<T>` and wrap body in `Ok()`

### ISSUE THREAD

**Issue by Boscop** [dtolnay/anyhow#127]
Suggestion:
Add an attribute proc-macro to wrap a function's return type `T` in `anyhow::Result<T>` and wrap its body in `Ok()`. Similar to what is written here:
https://github.com/withoutboats/fehler#the-throws-attribute
Except without the `throws` stuff. Just to have a concise attribute to make a function fallibe, such that its return type is changed from `T` to `anyhow::Result<T>` and its body is wrapped in `Ok()` because it gets annoying to have to do that manually (every time a function has to be changed from infallible to fallible because it now calls a fallible function).
The Ok-wrapping would work like in `try {}`, except that it should also work for `return`ed values (the proc-macro iterates over `return` statements in the body and wraps their values).

So that one could write e.g.:
```rust
#[fallible]
fn foo(arg: A) -> T {
    let x = bar()?;
    if x == XX {
        return ASD;
    }
    x*x
}
```
And it gets turned into:
```rust
fn foo(arg: A) -> anyhow::Result<T> {
    try {
        let x = bar()?;
        if x == XX {
            return Ok(ASD);
        }
        x*x
    }
}
```

The goal is to reduce the necessary code changes when having to change a function from being infallible to fallible, which is usually caused by it having to now call a fallible function:
The only changes necessary would be writing `#[fallible]` and writing `?` after that fallible function that is called in the body (`bar` in the example above).

**Comment by dtolnay** [comment]
I would prefer not to build this into this crate.
