### ISSUE TITLE
Would this be worth exploring adding to std?

### ISSUE THREAD

**Issue by mehcode** [dtolnay/anyhow#13]
First, this crate is awesome. I feel like Rust's error story is starting to feel really ergonomic.
This crate looks like a very nice Error type to reach for when working with a leaf/application crate.

Have you thought about working towards adding it to `std` ?
 
 * `anyhow::Error` could be added as `std::error` ( as a pseudo-primitive ) via the same hack that `i32` and `std::i32` are merged
 * `std::error` could be a very good default for various `Err`, `Error`, and `E` type parameters
 * `std::error` in a future edition could be added to the prelude as just `error`

**Comment by dtolnay** [comment]
I am open to that, but since this crate just came out yesterday it's a bit early to say. I think if we still think this is the best possible approach after ~12 months then that could be good justification for a std::error RFC.

**Comment by brightly-salty** [comment]
Bumping as it's been 14 months (making "later" now) since the above comment. I do feel like this is the best possible approach to Rust error handling. How should exploring adding to std proceed if it is still viable?

**Comment by dtolnay** [comment]
[RFC 2820](https://github.com/rust-lang/rfcs/pull/2820) has some discussion on a standard type erased error type.

There is also now an error handling project group (https://github.com/rust-lang/project-error-handling) whose purview such a proposal would be under.

**Comment by dtolnay** [comment]
The error handling project group clearly knows about this crate, so I don't think I need to keep this issue around. Closing and will leave it to them as far as what goes in std.
