### ISSUE TITLE
Implement the trait std::process::Termination for anyhow::Result

### ISSUE THREAD

**Issue by MrTact** [dtolnay/anyhow#131]
std::process::Termination is a relatively new api. In current builds of rustc, anything you return from main must implement this trait. Therefore you can no longer return anyhow::Result from main because it doesn't implement it. 

Looks like the implementation is pretty straightforward, shouldn't take long to do.

std documentation on the trait: https://doc.rust-lang.org/std/process/trait.Termination.html
github issue tracking development of the trait: https://github.com/rust-lang/rust/issues/43301

**Comment by MrTact** [comment]
Hmm. This is really weird. Not sure why this wouldn't be the case, since anyhow::Result is just a type alias for core::Result. Unless maybe it hasn't been and/or won't be implemented for core?

**Comment by dtolnay** [comment]
I believe returning anyhow::Result from main is already supported. There is an appropriate Termination impl for Result in the standard library.

```rust
fn main() -> anyhow::Result<()> {
    Ok(())
}
```
