### ISSUE TITLE
Feature Request: #[context] attribute for functions

### ISSUE THREAD

**Issue by jhwgh1968** [dtolnay/anyhow#138]
I really love this crate. The `Context` trait's error messages are very nice looking.

In fact, I love it so much, I want every single error produced by my binary to be in that style! But to do that, this is how my code has to look:

```rust
let s = String::new();
let mut f = std::fs:::File::open("foo.cfg").context("Reading configuration")?;
f.read_to_string(&mut s).context("Reading configuration")?;
let cfg: ProgramConfig = toml::from_str(&s).context("Reading configuration")?;
// ...
```

Every single time I do a question mark, everywhere in my code, I need to remember to type `.context()`, and what string I picked for that region.

On even the 1,000 line project I'm working on right now, that's a lot of contexts! And I forget, I'm back to the "unhelpful" error message style -- on an error I won't actually hit until much later, according to Murphy's Law. I'd much rather be able to define a _context scope_ that applies to _all_ errors within that scope.

While I looked into an `anyhow::context!` macro, I found it to be too ugly. Since most context changes are at function boundaries, I would thus propose this new attribute:

```rust
#[anyhow::context("Reading configuration")]
pub(crate) fn read_config_file(path: &Path) -> anyhow::Result<ProgramConfig> {
    /* code goes here, and every single Error will be annotated with that context  */
}
```

If this would be acceptable, I would happily implement it myself.

**Comment by jhwgh1968** [comment]
Reading my example, I suppose one might ask, "why not just call the function and then put a `.context()` on the result before it is re-thrown?"

Because if the function is called in 4 different places (like `read_config_file` will be, across different command-line utilities within the same package), then that still means I have to put a context on it four times.

Even more importantly (and more difficult for me), I have to make sure the string is the same across all those different locations. After all, if I see two slightly different messages, I'll go looking for two different pieces of code, and the end user (who will also see them) think something different was going on.

This attribute anchors the context to the _callee_, rather than the _caller_. That is what I really want to achieve.

**Comment by dtolnay** [comment]
I don't want this in this library, but https://github.com/yoshuawuyts/context-attribute does something similar.

**Comment by jhwgh1968** [comment]
Thanks for the pointer, @dtolnay. I'll look into it.
