### ISSUE TITLE
ensure_eq

### ISSUE THREAD

**Issue by imbolc** [dtolnay/anyhow#140]
`ensure!` feels conceptually close to `assert!`. Should we also have `ensure_eq!` with a message showing compared arguments as `assert_eq` does?

**Comment by zedseven** [comment]
What's the status on this? I too would like this feature, and the PR for it was submitted a while ago.

**Comment by Mononofu** [comment]
In addition, it would also be useful to have variants for other comparison operators - `ensure_lt`, `ensure_le`, `ensure_gt`, `ensure_ge`.

`ensure_some` would also be nice.

Automatically including both the names and values of the expressions being compared makes checking of pre- and post-conditions much more concise, increasing the chance that users will do so.

See e.g. an example of these functions in [TensorFlow](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/default/logging.h#L410).

**Comment by dtolnay** [comment]
These are handled by `ensure!` without needing a litany of `ensure_eq`/`ensure_lt`/`ensure_le`/`ensure_gt`/`ensure_ge`/`ensure_ne`/&hellip; macros.

```rust
ensure!(state_i < traj.timesteps.len());
```

```console
Condition failed: `state_i < traj.timesteps.len()` (40 vs 14)
```
