### ISSUE TITLE
add helper to improve context reporting

### ISSUE THREAD

**Issue by rkuhn** [dtolnay/anyhow#141]
First off: `anyhow` is awesome! It is a small, targeted library solving its part of the problem space. Which is why I’d like to ask whether the following might be considered within this space.

The fundamental unit of abstraction and reuse is the function. A function has a signature and a purpose (and sometimes a name). Within the somewhat large codebase I’m working on we have the following issue:

```rust
let result = fulfil_some_purpose_with_name(the_name)
    .with_context(|| format!("doing the purpose for {}", the_name))?;
```

This is because fulfilling that purpose has an implementation with several fallible steps, like so:

```rust
fn fulfil_some_purpose_with_name(name: &str) -> Result<SomeThing> {
    let path = get_file_for_name(name)?;
    let info = read_info(path)?;
    if perform_some_checks(info)? {
        write_audit_log(info)?;
        Ok(compute_result(info))
    } else {
        Err(anyhow!("check failed for {}", name))
    }
}
```

I consider this to be a responsibility leak (or a layering violation) in that the context is determined within the function but in practice all callers need to attach it from the outside. A small utility function could change this:

```rust
fn fulfil_some_purpose_with_name(name: &str) -> Result<SomeThing> {
    with_context(format!("doing the purpose for {}", name), || {
        let path = get_file_for_name(name)?;
        let info = read_info(path)?;
        if perform_some_checks(info)? {
            write_audit_log(info)?;
            Ok(compute_result(info))
        } else {
            Err(anyhow!("check failed for {}", name))
        }
    }
}
```

Of course I can write this function myself. The purpose of this issue is to ask whether this is considered good or bad practice and how I am possibly misusing `anyhow` so far 😀.

**Comment by dtolnay** [comment]
I think I would prefer not to build something into this crate for this.

**Comment by dtolnay** [comment]
An attribute macro would be less obtrusive than wrapping all your function bodies in a closure. That could be a neat project for someone.

```rust
#[context = "doing the purpose for {name}"]
fn fulfil_some_purpose_with_name(name: &str) -> Result<SomeThing> {
```

**Comment by rkuhn** [comment]
Thanks for your quick response! By “neat project”, do you mean “in your own crate” or “as a pull request”?

**Comment by dtolnay** [comment]
It would be separate from this crate.
