### ISSUE TITLE
cargo install grcov err 0433 on Ubuntu 20

### ISSUE THREAD

**Issue by TCeason** [dtolnay/anyhow#146]
run `cargo install grcov --verbose`

```
rustc --version 
rustc 1.51.0 (2fd73fabe 2021-03-23)
```

```
error[E0433]: failed to resolve: could not find `addr_of` in `ptr`
   --> /home/eason/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.40/src/error.rs:606:14
    |
606 |         ptr::addr_of!((*unerased.as_ptr())._object) as *mut E,
    |              ^^^^^^^ could not find `addr_of` in `ptr`

error[E0433]: failed to resolve: could not find `addr_of` in `ptr`
   --> /home/eason/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.40/src/error.rs:647:22
    |
647 |                 ptr::addr_of!((*unerased.as_ptr())._object) as *mut E,
    |                      ^^^^^^^ could not find `addr_of` in `ptr`

```

**Comment by TCeason** [comment]
I'm not sure the err is relation with https://github.com/dtolnay/anyhow/commit/ef082670ea0521eb5ab1f33119a64ac3896dda5e#diff-97e25e2a0e41c578875856e97b659be2719a65227c104b992e3144efa000c35eR606

**Comment by BohuTANG** [comment]
Same issues here, grcov action build failed as the same error.
It caused by this patch:
https://github.com/dtolnay/anyhow/commit/ef082670ea0521eb5ab1f33119a64ac3896dda5e

I have try revert it and works well.
Thanks for fixing.

**Comment by dtolnay** [comment]
This is probably because of the old nightly that you've pinned in https://github.com/datafuselabs/datafuse/blob/ad705559092f5f9ed8442eeeea310001058a1379/rust-toolchain. Assuming the same for @TCeason. This crate does not support old nightlies; the expectation is that if you are using a nightly toolchain, then you are remaining on top of recent nightly changes.

**Comment by BohuTANG** [comment]
Thanks @dtolnay

**Comment by TCeason** [comment]
Fixed, thx.
```
rustc -V
rustc 1.53.0-nightly (673d0db5e 2021-03-23)

```
