### ISSUE TITLE
Displaying a whole Chain

### ISSUE THREAD

**Issue by birkenfeld** [dtolnay/anyhow#15]
For logging errors ergonomically, it would be nice to be able to `Display` a `Chain`. The `impl Display for Error` only formats the highest level error, so it's in many use cases just a context without the cause.

**Comment by dtolnay** [comment]
The Debug impl does show the list of causes, and backtrace if there is one. Does that work for your use case? I wanted to stay away from fancy layout in the Display impl because what's appropriate formatting for different use cases is so variable.

**Comment by birkenfeld** [comment]
The Debug impl is too verbose for my needs; what I had in mind is "<thiserror>: <cause>: <cause>". Could this maybe selected by the "alternate format" flag for the `Error` display?

I understand you don't want to "bless" some more complicated formatting, but I suspect that many users would love a built-in way to get a quick error description along the whole chain.

**Comment by dtolnay** [comment]
Added `<thiserror>: <cause>: <cause>` as the {:#} format in 1.0.20:
https://github.com/dtolnay/anyhow/releases/tag/1.0.20.

**Comment by birkenfeld** [comment]
great, thanks!
