### ISSUE TITLE
FR: integration with log crate

### ISSUE THREAD

**Issue by freopen** [dtolnay/anyhow#152]
I often write pretty uncomfortable code when processing `anyhow::Result<()>` just to call `error!()` on it. E.g. when I implement a trait function that doesn't allow returning `Result`, or when I do some call for side effects and I don't worry too much if it ends with an error. I was thinking that it would be very useful to have some basic integration with log crate. For example:

```rust
some_noncritical_call().log_error();
// is equivalent to:
if let Err(err) = some_noncritical_call() {
  error!("{:?}", err);
}
```

```rust
anyhow_log_error!{
  some_noncritical_call()?.another_noncritical_call()?;
}
// is equivalent to:
fn noncritical_call_chain() -> Result<()> {
  some_noncritical_call()?.another_noncritical_call()?;
  Ok(())
}
noncritical_call_chain().log_error();
```

**Comment by dtolnay** [comment]
I am not interested in building this into the anyhow crate &mdash; but someone could build the API you showed as extension methods provided by a separate crate.
