### ISSUE TITLE
'cargo clippy' fails with rustc version 1.40.0

### ISSUE THREAD

**Issue by soenkehahn** [dtolnay/anyhow#154]
The [ci configuration](https://github.com/dtolnay/anyhow/blob/master/.github/workflows/ci.yml#L42) suggests that `anyhow` supports `rustc` version `1.34.0` and up. Here's an example project that uses version `1.40.0` of `rustc`: https://github.com/soenkehahn/anyhow-clippy-experiment. `cargo build` and `cargo test` in that repo work just fine, but `cargo clippy` fails with the error pasted below. Is using `anyhow` as a dependency **and** using `cargo clippy` not supported for older versions of `rustc`? Or is this a bug?

Here's the error:

```
error: error reading Clippy's configuration file `/home/shahn/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.40/.clippy.toml`: unknown field `msrv`, expected one of `blacklisted-names`, `cognitive-complexity-threshold`, `cyclomatic-complexity-threshold`, `doc-valid-idents`, `too-many-arguments-threshold`, `type-complexity-threshold`, `single-char-binding-names-threshold`, `too-large-for-stack`, `enum-variant-name-threshold`, `enum-variant-size-threshold`, `verbose-bit-mask-threshold`, `literal-representation-threshold`, `trivial-copy-size-limit`, `too-many-lines-threshold`, `third-party` at line 1 column 1

error: aborting due to previous error

error: could not compile `anyhow`.
```

**Comment by dtolnay** [comment]
That's right -- this crate supports old versions of rustc and cargo but not old versions of clippy.

**Comment by soenkehahn** [comment]
Thanks!
