### ISSUE TITLE
Compile probe does not take Cargo rustc configuration into account

### ISSUE THREAD

**Issue by jonhoo** [dtolnay/anyhow#156]
The compile probe just invokes `rustc` directly, without including relevant cargo configuration. This causes problems in environments where that configuration may change whether or not backtrace is available (or compiles):

```bash
cargo new anyhow-issue
cd anyhow-issue
mkdir .cargo
echo '[build]' >> .cargo/config.toml
echo 'rustflags = ["-Zallow-features="]' >> .cargo/config.toml
echo 'anyhow = "1"' >> Cargo.toml
rustup override set nightly
cargo check
```

produces

```
    Updating crates.io index
  Downloaded anyhow v1.0.41
  Downloaded 1 crate (34.6 KB) in 0.68s
   Compiling anyhow v1.0.41
error[E0725]: the feature `backtrace` is not in the list of allowed features
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.41/src/lib.rs:213:32
    |
213 | #![cfg_attr(backtrace, feature(backtrace))]
    |                                ^^^^^^^^^

error[E0658]: use of unstable library feature 'backtrace'
 --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.41/src/backtrace.rs:2:33
  |
2 | pub(crate) use std::backtrace::{Backtrace, BacktraceStatus};
  |                                 ^^^^^^^^^
  |
  = note: see issue #53487 <https://github.com/rust-lang/rust/issues/53487> for more information
  = help: add `#![feature(backtrace)]` to the crate attributes to enable
...
```

Taking _everything_ into account is probably too tall of an order, but the [Cargo environment variables](https://doc.rust-lang.org/cargo/reference/environment-variables.html) should get us pretty far. In particular, if set, anyhow should probably take into account these three:

 - `CARGO_BUILD_RUSTC`
 - `CARGO_BUILD_RUSTC_WRAPPER`
 - `CARGO_BUILD_RUSTFLAGS`

Together, those should encapsulate _most_ of the rustc configuration in cargo.

**Comment by dtolnay** [comment]
Ah, good call. I would accept a PR to fix this.

**Comment by jonhoo** [comment]
Ooof, looks like those environment variables are only used to _configure_ said settings. And the variables Cargo [_sets_ for build scripts](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts) does not include the wrapper nor rustflags. I'll follow up with the Cargo team.

**Comment by jonhoo** [comment]
Filed https://github.com/rust-lang/cargo/issues/9600

**Comment by jonhoo** [comment]
Submitted fix in https://github.com/rust-lang/cargo/pull/9601, though this means we'll have to wait a while to actually _implement_ this fix.
