### ISSUE TITLE
Consider adding #[cold] to anyhow functions

### ISSUE THREAD

**Issue by stepancheg** [dtolnay/anyhow#165]
Have a look at [this example in compiled explorer](https://rust.godbolt.org/z/jjcczY718):

```
pub unsafe fn foo() -> Result<(), AnyhowError> {
    Ok(some_op()?)
}
```

When `from` is marker `#[cold]`, default path for `foo` is this:

```
example::foo:
        push    rax
        call    qword ptr [rip + some_op@GOTPCREL]
        cmp     al, 4
        jne     .LBB6_2
        xor     eax, eax
.LBB6_3:
        lea     rdx, [rip + .L__unnamed_1]
        pop     rcx
        ret
```

Now remove `#[cold]`, and generated code is now:

```
example::foo:
        push    r14
        push    rbx
        push    rax
        call    qword ptr [rip + some_op@GOTPCREL]
        mov     rbx, rax
        cmp     bl, 4
        jne     .LBB5_2
        xor     eax, eax
        jmp     .LBB5_4
.LBB5_2:
        // ... error handling
.LBB5_4:
        lea     rdx, [rip + .L__unnamed_1]
        add     rsp, 8
        pop     rbx
        pop     r14
        ret
```

The difference is between no-cold and cold:
* three registered pushed on the stack instead of one
* default path takes a jump forward, while in cold version there's no unnecessary jumps in cold version
* it is 8 instructions in default path for cold version, and it is 14 instructions in no-cold version

I tried locally apply this patch to anyhow (to `from` because we don't use other functions a lot):

```
diff --git a/src/error.rs b/src/error.rs
index 92bb63d..db1b76b 100644
--- a/src/error.rs
+++ b/src/error.rs
@@ -515,6 +515,7 @@ impl<E> From<E> for Error
 where
     E: StdError + Send + Sync + 'static,
 {
+    #[cold]
     fn from(error: E) -> Self {
         let backtrace = backtrace_if_absent!(error);
         Error::from_std(error, backtrace)
```

In our benchmark, this change resulted in 0.3% reduction of binary size, and benchmark for an application which uses anyhow heavily to propagate errors was sped up by 0.5%.

```
A: n=374 mean=65.808 std=1.999 se=0.103 min=62.592 max=73.481 med=65.344
B: n=374 mean=65.444 std=1.937 se=0.100 min=62.229 max=71.456 med=64.993
A: distr=[   ▁▂▅▂▆▄█▆▅▆▆▃▂▃▂▃▁▁▃▁▂▂▃▃▄▃▃▆▃▄▃▁▁▁▁                       ]
B: distr=[ ▁▁▂▃▅▄█▇▆▆▄▃▃▄▂▁▂▂▄▂▁▃▁▅▃▃▆▂▄▄▁▂▁▂▂▁ ▁                      ]
B/A: 0.994 0.990..0.999 (95% conf)
```

When an error function is annotated with `#[cold]` LLVM considers code paths leading to this function less likely and optimizes code for non-cold paths. Without `#[cold]` LLVM considers `Ok` and `Err` equally likely and tried to optimize execution for both paths.

Perhaps, `#[cold]` can be enabled as a feature, e. g. `#[cfg_attr(feature = "cold", cold)]`.

CC @ndmitchell

**Comment by dtolnay** [comment]
I would accept a PR judiciously adding #\[cold\] in the place where you've observed that it matters.
