### ISSUE TITLE
another possible member of the Context trait

### ISSUE THREAD

**Issue by stevedonovan** [dtolnay/anyhow#17]
We've been using a little minimal crate for our modest error handling purposes, and one thing that turned out very useful was `context_with`:

```rust
fs::read_to_string(&path).context_with("cannot open",&path)?;
```
which is entirely equivalent to:
```rust
fs::read_to_string(&path).with_context(|| format!("cannot open {:?}", path))?;
```
I am not entirely sure of the name `context_with` (maybe `context_debug`?) but it's certainly a nice convenience in the common case where the error needs to refer to the string, path, etc that was the source of the trouble.

**Comment by dtolnay** [comment]
Thanks! I would prefer not to add this for now, but you should be able to implement it in your codebase as an extension trait on top of anyhow::Context:

```rust
use anyhow::{Context, Result};
use std::fmt::Debug;
use std::fs;

pub trait ContextWith<T, E>: Context<T, E> {
    fn context_with(self, msg: &str, with: impl Debug) -> Result<T>;
}

impl<T, E, R> ContextWith<T, E> for R where R: Context<T, E> {
    fn context_with(self, msg: &str, with: impl Debug) -> Result<T> {
        self.with_context(|| format!("{} {:?}", msg, with))
    }
}

fn main() -> Result<()> {
    let path = "/nonexist";
    fs::read_to_string(&path).context_with("cannot open", &path)?;
    Ok(())
}
```

**Comment by stevedonovan** [comment]
In fact, just after I opened the issue I found I could add it _anyway_ in this way, so I was happy.
