### ISSUE TITLE
Clarify how to print out backtraces in the docs

### ISSUE THREAD

**Issue by samuela** [dtolnay/anyhow#175]
The docs show nice backtrace-y things like:
```
Error: Failed to read instrs from ./path/to/instrs.json

Caused by:
    No such file or directory (os error 2)
```
from https://docs.rs/anyhow/1.0.44/anyhow/trait.Context.html. However, I haven't been able to find any explanation of how to print out these backtraces directly. I understand that if I let my Result types bubble up all the way to `main`, I'll probably see these things, but what if I'm implementing something like a web server and I'd like to log some errors in the handling of requests?

**Comment by dtolnay** [comment]
I added a link from the `Context` trait docs to your second link.
