### ISSUE TITLE
Make adding paths to I/O errors even simpler

### ISSUE THREAD

**Issue by sffc** [dtolnay/anyhow#176]
Currently the docs suggest doing something like

```rust
std::fs::read(path)
        .with_context(|| format!("Failed to read instrs from {}", path))?
```

This is such a common case that the above code just becomes boilerplate. It would be nicer if it were just

```rust
let content = fs::read(path).with_context_path(path)?;
```

This should work only on `std::io::Result`, and the error message should concatenate the ErrorKind from the io::Error with the path, such that an example error is something like `"PermissionDenied: foo.txt"`.

*Also filed against eyre as https://github.com/yaahc/eyre/issues/62*

**Comment by dtolnay** [comment]
I have the same reaction to this as yaahc's comment in the link, and I would prefer not to add this.
