### ISSUE TITLE
Breaking changes in minor update

### ISSUE THREAD

**Issue by optizone** [dtolnay/anyhow#188]
Hi, I'm trying to build a project that depends on log4rs which depends on anyhow version 1, and I'm having troubles with that due to recent update of anyhow. 

```cargo tree -p log4rs
log4rs v1.0.0
├── anyhow v1.0.46
```

Error:
```
error: 1 positional argument in format string, but no arguments were given
   --> /home/optizone/.cargo/registry/src/github.com-1ecc6299db9ec823/log4rs1.0.0/src/append/rolling_file/policy/compound/roll/fixed_window.rs:261:46
    |
261 |             bail!("pattern does not contain `{}`");
    |                                              ^^

```

I'm not sure what to do with this issue (other than editing cargo registry manually), and I'm consernd about other crates that can be affected by this update. 

So if you knwo what to do please help. Or fix this change.

Thank you

P.S.
I also heard that it is not recommended to make this kind of breaking changes in minor updates (not trying to be rude or anything).

**Comment by trevyn** [comment]
You can override the version until this is fixed in `log4rs` (should open an issue there if they’re not already aware); put this in your project’s `Cargo.toml`:

```
[patch.crates-io]
anyhow = "1.0.45"
```

**Comment by dtolnay** [comment]
Sorry about the breakage - I have yanked that release for now. Will check what is going on in log4rs.

**Comment by optizone** [comment]
thank you ❤️
