### ISSUE TITLE
Function `anyhow::Ok` breaks `Ok` pattern matching when wildcard importing

### ISSUE THREAD

**Issue by N3xed** [dtolnay/anyhow#201]
When wildcard importing `anyhow` (`use anyhow::*`), the recently added function `anyhow::Ok` breaks pattern-matching because it shadows `Result::Ok` and thus causes build failures:

```
error[E0532]: expected tuple struct or tuple variant, found function `Ok`
   --> src\utils.rs:199:13
    |
199 |             Ok(result) => {
    |             ^^ not a tuple struct or tuple variant
    |
   ::: src\python.rs:12:23
    |
12  |     let version_str = cmd_output!(PYTHON, "--version")
    |                       -------------------------------- in this macro invocation
    |
```
In my view, this is a breaking change.

It's quite convenient to import all of `anyhow` at once, so I'd suggest moving this function into a module. Or it would need a new major version, but this may be overkill for such a small change.

**Comment by dtolnay** [comment]
Cross-crate glob imports are never supposed to be used for exactly this reason. Please see https://doc.rust-lang.org/1.56.0/cargo/reference/semver.html#minor-adding-new-public-items.

> This is not considered a major change because conventionally glob imports are a known forwards-compatibility hazard. Glob imports of items from external crates should be avoided.

**Comment by N3xed** [comment]
I've learnt something new, thanks.

**Comment by asayers** [comment]
> glob imports are a known forwards-compatibility hazard

True, but in practice I think this change is going to cause confusion.  It will break people's code, and most won't think to check the source for `#[doc(hidden)]` items.  I wouldn't be surprised if `rust/rust` receives bug reports from people mistaking this for a typechecker bug.

Why not include `fn Ok()` in the docs?

**Comment by kali** [comment]
Please reconsider this move. You're basically saying it's ok to punish people from having been lazy and wrote a harmless-looking global include. Aggravated by the fact the function is hidden from the documentation and out of convention style.
I've seen how weird the error generated by rustc, this is gonna make a lot of people waste a lot of time.

I have fixed my repos. But please, please, think of all these teams pulling their hair out right now and be nice to them. Please revert and yank this.

**Comment by dtolnay** [comment]
Folks, this crate is made for me to use, in the way that I want to use it. If you want to use glob imports your options are:

- don't use this crate;
- send a rustc PR to make it handle pattern matches on tuple variants even with a similarly named fn imported;
- send a rustc PR to improve its error messages.
