### ISSUE TITLE
version 1.0.49 breaks compatibility

### ISSUE THREAD

**Issue by njaard** [dtolnay/anyhow#207]
I was  building [intel-mkl-tool](https://github.com/rust-math/intel-mkl-src) and I found that switching from 1.0.48 to 1.0.49 (and 50 and 51) breaks compilation, which violates semver.

# Steps to reproduce
1. `git clone git@github.com:rust-math/intel-mkl-src.git`
2. `cd intel-mkl-src/intel-mkl-tool`
3. `cargo build --release` produces errors like this (trimmed for brevity):

```
error[E0532]: expected tuple struct or tuple variant, found function `Ok`
  --> intel-mkl-tool/src/entry.rs:75:16
   |
75 |         if let Ok(dir) = std::env::var("OUT_DIR") {
   |                ^^ not a tuple struct or tuple variant
   |
help: consider importing one of these items instead
   |
1  | use core::result::Result::Ok;
   |
1  | use std::result::Result::Ok;
   |

error[E0308]: mismatched types
  --> intel-mkl-tool/src/download.rs:34:17
   |
34 |                 Ok(new_data.len())
   |                 ^^^^^^^^^^^^^^^^^^ expected enum `WriteError`, found struct `anyhow::Error`
   |
   = note: expected enum `std::result::Result<_, WriteError>`
              found enum `std::result::Result<_, anyhow::Error>`

error[E0308]: `match` arms have incompatible types
  --> intel-mkl-tool/src/config.rs:15:41
   |
15 | #[derive(Debug, Clone, Copy, PartialEq, Display)]
   |                                         ^^^^^^^
   |                                         |
   |                                         expected struct `std::fmt::Error`, found struct `anyhow::Error`
   |                                         `match` arms have incompatible types
16 | pub enum LinkType {
17 |     #[display(fmt = "static")]
   |       ------- this is found to be of type `std::result::Result<(), std::fmt::Error>`
18 |     Static,
19 |     #[display(fmt = "dynamic")]
   |       ------- this is found to be of type `std::result::Result<(), std::fmt::Error>`
   |
   = note: expected enum `std::result::Result<_, std::fmt::Error>`
              found enum `std::result::Result<_, anyhow::Error>`
   = note: this error originates in the derive macro `Display` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Then change `intel-mkl-tool/Cargo.toml` so that it has `anyhow="1.0.48"` and it builds cleanly.

Note that intel-mkl-tool appears unmaintained.

**Comment by dtolnay** [comment]
This does not violate semver &mdash; please see https://doc.rust-lang.org/1.56.0/cargo/reference/semver.html#minor-adding-new-public-items.

> This is not considered a major change because conventionally glob imports are a known forwards-compatibility hazard. Glob imports of items from external crates should be avoided.

The crate you linked contains a `use anyhow::*` which means it has opted into being broken by minor changes of this kind. That decision is between you and the intel-mkl-tool author.
