### ISSUE TITLE
Feature-gate `Context` for `Option`?

### ISSUE THREAD

**Issue by smoelius** [dtolnay/anyhow#214]
Would you consider a PR to put the [`Context` implementation for `Option`](https://github.com/dtolnay/anyhow/blob/f871e2fefcd10dab7b88af2fc27e2f7e0cfa1990/src/context.rs#L82-L97) behind a feature?

At present, it is easy to wind up with a mix of `ok_or_else` and `with_context` applied to `Option` instances.

While I can see arguments for either, providing an enabled-by-default feature that one could turn off would help those who prefer `ok_or_else`.

**Comment by dtolnay** [comment]
I would prefer not to change this, but one doesn't have to use this crate's `Context` trait. You can define an alternative `Context` trait in your own codebase with only the impls you want.

**Comment by smoelius** [comment]
Understood. Thanks.
