### ISSUE TITLE
Allow captured identifiers

### ISSUE THREAD

**Issue by SuperCuber** [dtolnay/anyhow#218]
In the newest Rust 1.58 release, there's a new feature for [captured identifiers in format strings](https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings).

While `log`'s macros supports the new syntax immediately, it seems that `anyhow!` and `bail!` silently ignore it. So `bail!("{test}")` will return with an error containing a literal `{test}` string.

If this is not possible to implement for some technical reason I think it's important to warn/error if such syntax is encountered.

**Comment by dtolnay** [comment]
It seems to work: https://play.rust-lang.org/?edition=2021&gist=6e5aeb5b326447170453626997f3ec58

**Comment by SuperCuber** [comment]
@dtolnay Strange, for me not only it showed the literal string, it even gave a warning for an unused variable...

Seems like updating from `anyhow 1.0.44` to `1.0.52` fixes it though. ¯\_(°ペ)_/¯
