### ISSUE TITLE
Call bail on an interop with thiserror

### ISSUE THREAD

**Issue by nipunn1313** [dtolnay/anyhow#220]
Would love to be able to call bail in this kind of situation:

(this is a cargo-play compatible snippet)
```rust
//# thiserror = "*"
//# anyhow = "*"
#[derive(thiserror::Error, Debug)]
#[error(transparent)]
pub struct MyError {
        #[from] source: anyhow::Error,
}

fn main() -> Result<(), MyError> {
        anyhow::bail!("Oh no!")
}
```

Currently it gives
```
error[E0308]: mismatched types
  --> src/main.rs:10:9
   |
10 |         anyhow::bail!("Oh no!")
   |         ^^^^^^^^^^^^^^^^^^^^^^^ expected struct `MyError`, found struct `anyhow::Error`
   |
   = note: this error originates in the macro `$crate::anyhow` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0308`.
error: could not compile `p48ozyvdrnwx1vn2ftmvf68rykhuv` due to previous error
```

Workarounds:
```rust
fn main() -> Result<(), MyError> {
    Err(anyhow::anyhow!("Oh no!"))?
}
```
or
```rust
fn main() -> Result<(), MyError> {
    return Err(anyhow::anyhow!("Oh no!").into())
}
```

My understanding is that bail is intended to be syntactic sugar for similar situations. It seems plausible to extend it here with a well placed `into()`

**Comment by nipunn1313** [comment]
This isn't just specialcasing thiserror.
It's extending it to work in any function whose return type is a Result with an error that is `From<anyhow::Error>`

**Comment by dtolnay** [comment]
The restriction on the return type is intentional. The use cases that anyhow is intended for involve application code in which almost every Result return uses anyhow::Error.
