### ISSUE TITLE
Can I change the `Error` prefix?

### ISSUE THREAD

**Issue by mauro-balades** [dtolnay/anyhow#222]
![Screenshot_20220206_195209](https://user-images.githubusercontent.com/91018726/152696776-f7ab982a-d132-4193-b479-ae319820f736.png)

^ I was hoping that I could change that prefix to something else... If I can, how?

**Comment by dtolnay** [comment]
Nothing in this crate puts that prefix there. Something else in whatever you are doing produces the prefix.

**Comment by mauro-balades** [comment]
hm....
