### ISSUE TITLE
Nightly time bomb

### ISSUE THREAD

**Issue by est31** [dtolnay/anyhow#23]
Right now, the crate is checking in build.rs if nightly is present, and if it is, enables the backtrace cfg *without asking the user*, enabling the backtrace nightly feature: https://github.com/dtolnay/anyhow/blob/master/src/lib.rs#L174

Unstable Rust features can and often do change before stabilization though. This means that this crate is a time bomb for nightly users in the event of changes of the backtrace feature. Instead, this crate should make its backtrace support entirely opt-in for the user.

**Comment by dtolnay** [comment]
Thanks, I replaced this with something more reliable in #24.

**Comment by est31** [comment]
@dtolnay thank you! While not perfect, it's much better now.
