### ISSUE TITLE
Build fails when -Zallow-features doesn't include backtrace

### ISSUE THREAD

**Issue by bjorn3** [dtolnay/anyhow#230]
`-Zallow-features` makes it possible to restrict which unstable features are used. Anyhow uses the backtrace feature if it detects it to be available. This check uses `CARGO_ENCODED_RUSTFLAGS` which contains the rustflags required for compiling for the host. When using `RUSTFLAGS="-Zallow-features=" cargo build --target x86_64-unknown-linux-gnu`, `CARGO_ENCODED_RUSTFLAGS` doesn't contain `-Zallow-features=`, so anyhow thinks the backtrace feature is available, however when compiling anyhow for the target `-Zallow-features=` is passed to rustc and thus the compilation fails.

**Comment by vi** [comment]
Implemented a pull request with additional negative Cargo feature to turn off all backtracing: #256.

**Comment by dtolnay** [comment]
I was not able to reproduce this. Would you be able to provide a complete Cargo.toml and cargo/rustc version that reproduces this issue?

**Comment by jaskij** [comment]
When building 1.0.62 using rust 1.59 I am getting:

```
   Compiling anyhow v1.0.62
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /home/jaskij/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.62/src/lib.rs:214:32
    |
214 | #![cfg_attr(backtrace, feature(backtrace))]
    |                                ^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
```

Rust version:

```
$ rustc --version
rustc 1.59.0 (9d1b2106e 2022-02-23)
```

**Comment by bjorn3** [comment]
I can't reproduce this anymore either.
