### ISSUE TITLE
implement From for Option

### ISSUE THREAD

**Issue by laralove143** [dtolnay/anyhow#232]
i’m aware of the context method but in a lot of cases the extra given message is just as useful as a generic “Option<TypeName> is None” so calling this method over and over is kind of boilerplate.. i’m doing this to sort of implement it: ```rs
trait ToError<T> {
  fn to_err(self) -> Result<T, anyhow::Error>;
}

impl<T> ToError<T> for Option<T> {
  fn to_err(self) -> Result<T, anyhow::Error> {
    match self {
      Some(s) => Ok(s),
      None => Err(anyhow::anyhow!("the Option<{}> is None", std::any::type_name::<T>())),
    }
  }
}

fn bar() -> Option<char> {
    Some('a')
}

fn baz() -> Option<char> {
    None
}

fn foo() -> anyhow::Result<char> {
  bar().to_err()?;
  baz().to_err()?;
  Ok('a')
}

fn main() {
  let res = foo();
  println!("{res:?}");
}``` but it should be possible to use `?` directly without a `to_err()` method with an in-crate implementation, what do you think

**Comment by dtolnay** [comment]
I would not want to add this. "Option is None" is usually not a sufficient amount of context about what went wrong.

**Comment by laralove143** [comment]
isn't it possible to give the backtrace as well?

**Comment by WhyNotHugo** [comment]
Try:

```rust
use anyhow::Context;

my_option.context("the thing was None")?;
```
