### ISSUE TITLE
Question regarding coding style

### ISSUE THREAD

**Issue by tomers** [dtolnay/anyhow#235]
Hey, I got this code snippet, which I rather dislike. I have a feeling it can be written better, but I could not find similar mechanism in Anyhow...

```
let action = Action::from_str(action_str);
if action.is_err() {
    bail!("Failed to parse: {}", action.err().unwrap());
};
let action = action.unwrap();
```

I would expect some syntactic sugar in this form:
```
let action = Action::from_str(action_str).unwrap_or_bail_with(|err| "Failed to parse: {err}");
```
I'll be grateful if you could suggest a better exiting syntax to use, or consider adding similar function to what I have suggested above. Thanks!

**Comment by smoelius** [comment]
Maybe [`anyhow::Context`](https://docs.rs/anyhow/latest/anyhow/trait.Context.html#example) might suit your needs?

**Comment by tomers** [comment]
@smoelius , I would use `with_context`, but the issue is that I would like the error to be part of the context, i.e. `.with_context(|err| ...)` rather than `.with_context(|| ...)`.

**Comment by stevecheckoway** [comment]
@tomers, I think you want to use `map_err()` and `anyhow!()`.

```rust
let action = Action::from_str(action_str)
    .map_err(|err| anyhow!("Failed to parse: {err}"))?;
```

**Comment by tomers** [comment]
That's great, @stevecheckoway! Thanks.
Maybe consider adding this important example to the documentation. I believe it could help some users.
