### ISSUE TITLE
Enahncement: impl Context for TryFutureExt

### ISSUE THREAD

**Issue by detly** [dtolnay/anyhow#237]
The [futures crate](https://crates.io/crates/futures), which underpins almost every async crate currently in use, has a very useful trait [`TryFutureExt`](https://docs.rs/futures/latest/futures/future/trait.TryFutureExt.html#method.flatten_sink) which provides an async analogue to std's `Result`.

Anyhow's `Context` trait can't be applied to it directly, but can be used with it by:

```rust
let anyhow_res = some_fallible_op().map(|res| res.context("Could not do thing"));
```

Would you be interested me removing this slight amount of boilerplate so that `context()` can be called directly on `TryFutureExt` implementers? I'm happy to do the PR, I just want to know if you're interested.

If so, I'd assume you'd want it optional? If not, no worries.

**Comment by dtolnay** [comment]
I would prefer not to build this into this crate.

Thanks anyway for the suggestion!
