### ISSUE TITLE
[Question] How to chain anyhow errors ? 

### ISSUE THREAD

**Issue by Cheappie** [dtolnay/anyhow#238]
Hi, is it possible to chain anyhow error's ? For example `anyhow!(anyhow!(e).context("abc")).context("efg")`. I wonder if anyhow has concept of bubbling up and gaining more context along the way.

**Comment by vi** [comment]
Indeed, it is possible to chain errors and you have guessed the syntax correctly.

```rust
use anyhow::anyhow;

fn main() {
   let e = anyhow!(anyhow!("e").context("abc")).context("efg");
   eprintln!("{:#}", e);
}
```

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.87s
     Running `target/debug/playground`
efg: abc: e
```

[Playgroud link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0835ec752015e87e07c7e79b6fd3ec14)

**Comment by Cheappie** [comment]
@vi thank you for explanation, the problem was that I have been printing via Display trait, where actually debug is configured to print chain. Thank you again.

**Comment by vi** [comment]
> printing via Display trait

In the example above `Display` trait is used as well. The crucial thing is using alternate form character `#`. `Debug`-form errors may also contain context chains, but they are not user-friendly to see.
