### ISSUE TITLE
How to make Error cloneable and support context chaining

### ISSUE THREAD

**Issue by FredrikNoren** [dtolnay/anyhow#240]
Hi,

I have a situation where I need an Error to be Cloneable. I saw #7 and tried implementing something like this:

```rust
#[derive(Clone, Error)]
pub struct AssetError(Arc<anyhow::Error>);
impl From<anyhow::Error> for AssetError {
    fn from(err: anyhow::Error) -> Self {
        Self(Arc::new(err))
    }
}
impl std::fmt::Display for AssetError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}
impl std::fmt::Debug for AssetError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}


fn a() -> Result<(), AssetError> {
    Err(anyhow!("a").into())
}

fn b() -> Result<(), AssetError> {
    Ok(a().context("b")?)
}

fn c() -> Result<(), AssetError> {
    Ok(b().context("c")?)
}

fn main() {
   if let Err(e) = c() {
      eprintln!("{:#}", e); // Prints: "c: b", i.e. a is left out
   }
}
```

The one problem though is that it will only store the "latest" two contexts. Any idea how I could change that implementation to store the full context? Here's a playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2172afa004deb537f4c27d5e7bf54bc3

**Comment by dtolnay** [comment]
You haven't implemented a `source` method in AsserError's `Error` impl, so it's not possible for errors of type AssetError to be chained / be context for another error.

For your use case it sounds like you want `#[error(transparent)]` on AssetError (and remove the Display impl), since the `source` would need to be the same as the Arc\<anyhow::Error\>'s `source`.

In general you would need a `#[source]` attribute somewhere in the error in order to create chains of errors/contexts.

**Comment by FredrikNoren** [comment]
@dtolnay Awesome, that works. Thank you!

For anyone else seeing this, here's the final implementation I use:

```rust
#[derive(Clone, Error)]
#[error(transparent)]
pub struct AssetError(Arc<anyhow::Error>);
impl From<anyhow::Error> for AssetError {
    fn from(err: anyhow::Error) -> Self {
        Self(Arc::new(err))
    }
}
impl std::fmt::Debug for AssetError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}
```

**Comment by phiresky** [comment]
Just wanted to mention this since I had the same issue:

If you're not using thiserror as well as anyhow, instead of using `error(transparent)` you can implement StdError manually like this:

```rust
impl std::error::Error for AssetError {
  fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
    self.inner.source()
  }
}
```
