### ISSUE TITLE
Re-enable backtrace test on miri

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/anyhow#246]
8d25d6b2c9bb04c9f0d222ed6b900f696c0e7ebe will probably be possible to revert shortly.

https://github.com/rust-lang/miri/issues/2431
https://github.com/rust-lang/miri/pull/2436

**Comment by RalfJung** [comment]
What exactly does the build.rs probe do? I see it does an `--emit=metadata` call; if it expects any actual files to be created, then https://github.com/rust-lang/miri/pull/2436 is not enough. OTOH if https://github.com/rust-lang/miri/pull/2436 is enough then it should fix using miri+anyhow in cross-interpretation for a foreign target (which was likely broken before... or, looking at the code it doesn't check TARGET so I guess it doesn't work for cross-compilation anyway?).

**Comment by dtolnay** [comment]
I does not need any actual files written out by the rustc invocation. It's just looking for a success or fail exit code from a "check"-style build.

**Comment by RalfJung** [comment]
Okay, yeah that is like what autocfg does so it should work with that PR (and we'll have it on CI).

You might want to check autocfg's TARGET handling though, otherwise I am not sure what this does is correct for cross-compilation. The probe seems to always test the host, not the target.

**Comment by RalfJung** [comment]
Should be fixed in the latest nightly.

**Comment by dtolnay** [comment]
Thanks!
