### ISSUE TITLE
1.0.61 causes rebuilds after restarting VScode with rust-analyzer

### ISSUE THREAD

**Issue by NeoRaider** [dtolnay/anyhow#261]
Since updating one of my projects to `anyhow` 1.0.61
- rust-analyzer rechecks `anyhow` and everything that depends on it on each start of VScode
- Running `rust build` etc. in a terminal rebuilds `anyhow` and everything that depends on it after rust-analyzer rechecked it

For larger projects with anyhow deep in their dependency chain, these frequent rebuilds can get quite annoying.

**Comment by dtolnay** [comment]
Thanks for the report. This was put in as a workaround for the builds just altogether failing (https://github.com/rust-lang/rust-analyzer/issues/12973). There is a fix in https://rust-analyzer.github.io/thisweek/2022/08/15/changelog-142.html#fixes so we can just remove it and count on people to upgrade rust-analyzer.

**Comment by dtolnay** [comment]
Could you confirm whether this is gone with 1.0.62?

**Comment by NeoRaider** [comment]
Yes, working fine now, thanks!
