### ISSUE TITLE
How to use backtrace after stabilisation?

### ISSUE THREAD

**Issue by Morganamilo** [dtolnay/anyhow#262]
I can't quite figure out how to use backtrace now that it's stable.

The backtrace method is gone from the error type, however looking at the docs it says:

> If using the nightly channel, or stable with features = ["backtrace"], a backtrace is captured and printed with the error if the underlying error type does not already provide its own. In order to see backtraces, they must be enabled through the environment variables described in [std::backtrace](https://doc.rust-lang.org/std/backtrace/index.html#environment-variables):

This seems to imply it prints automatically now but it does not. Searching the docs for backtrace doesn't give any results.

**Comment by ArekPiekarz** [comment]
Which compiler version do you use? Backtrace is stabilized, but still only on nightly - it will arrive on the stable branch in Rust 1.65.

**Comment by Morganamilo** [comment]
I'm using nightly, where it's currently stable.

**Comment by ArekPiekarz** [comment]
I guess one would need to use the [Provider API](https://github.com/rust-lang/rust/issues/96024).

**Comment by Morganamilo** [comment]
I don't get what this has to do with me printing a backtrace.

**Comment by dtolnay** [comment]
It should still work as documented:

```rust
fn main() {
    let error = anyhow::Error::msg("huh");
    println!("{:?}", error);
}
```

```console
$ RUST_LIB_BACKTRACE=1 cargo run

huh

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
             at anyhow-1.0.64/src/error.rs:83:36
   1: repro::main
             at ./src/main.rs:2:17
   2: core::ops::function::FnOnce::call_once
             at /rustc/289279de116707f28cf9c18e4bbb8c6ec84ad75b/library/core/src/ops/function.rs:248:5
   …
  13: std::rt::lang_start_internal
             at /rustc/289279de116707f28cf9c18e4bbb8c6ec84ad75b/library/std/src/rt.rs:148:20
  14: std::rt::lang_start
             at /rustc/289279de116707f28cf9c18e4bbb8c6ec84ad75b/library/std/src/rt.rs:165:17
   …
  18: _start
```

or using `println!("{:#?}", error.backtrace())`:

```console
Backtrace [
    { fn: "anyhow::error::<impl anyhow::Error>::msg", file: "anyhow-1.0.64/src/error.rs", line: 83 },
    { fn: "testing::main", file: "./src/main.rs", line: 2 },
    { fn: "core::ops::function::FnOnce::call_once", file: "/rustc/289279de116707f28cf9c18e4bbb8c6ec84ad75b/library/core/src/ops/function.rs", line: 248 },
    …
    { fn: "std::rt::lang_start_internal", file: "/rustc/289279de116707f28cf9c18e4bbb8c6ec84ad75b/library/std/src/rt.rs", line: 148 },
    { fn: "std::rt::lang_start", file: "/rustc/289279de116707f28cf9c18e4bbb8c6ec84ad75b/library/std/src/rt.rs", line: 165 },
    …
    { fn: "_start" },
]
```

**Comment by Morganamilo** [comment]
Hey so I'm not home right now so I can't quite test this. But my code doesn't just println the error. I manually unwind the context to print it how I want. I would like some way to also print the backtrace manually.
