### ISSUE TITLE
Failed to compile in debug build

### ISSUE THREAD

**Issue by MedzikUser** [dtolnay/anyhow#264]
![image](https://user-images.githubusercontent.com/87065584/185093189-56a98d22-55fe-440d-bede-395614f63b69.png)

Project [servers](https://github.com/MedzikUser/servers)

In the release build version, it magically works

rustc 1.63.0 (4b91a6ea7 2022-08-08) stable-x86_64-unknown-linux-gnu (from rustup)

**Comment by dtolnay** [comment]
This is caused by certain versions of rust-analyzer. You would need to use a newer version of rust-analyzer.
