### ISSUE TITLE
should we call `.into()` in `bail!`?

### ISSUE THREAD

**Issue by M1cha** [dtolnay/anyhow#265]
The `bail` macro makes a lot of code a lot simpler but it can't be used when the return type isn't an anyhow error. If that type does implement `From<anyhow::Error>` the error can easily be converted by calling `.into()` though.

So would it make sense to make that change to the bail macro or are there any objections?

To put my words into code:
```rust
return $crate::__private::Err($crate::__anyhow!($msg).into())
```

**Comment by dtolnay** [comment]
The current behavior is intentional. See #112.
