### ISSUE TITLE
README does not explain what problem crate solves (how crate compares to std)

### ISSUE THREAD

**Issue by hkBst** [dtolnay/anyhow#272]
[README.md](https://github.com/dtolnay/anyhow#readme) contains minimal comparisons to similar crates (failure, thiserror), but does not contrast this crate's capabilities with what is possible with std. Some examples of awkward code one would have to write using just std, together with the replacements made possible by this crate would go a long way to doing that. Without this it is not clear what problem this crate is trying to solve.

**Comment by dtolnay** [comment]
I reread and I think this is fine as written. The readme describes the highlights of the crate, and if someone does not need those things then they can do without the crate.
