### ISSUE TITLE
Should Anyhow include features for library-specific integrations?

### ISSUE THREAD

**Issue by T-O-R-U-S** [dtolnay/anyhow#277]
Self-explanatory -- should `anyhow` include integrations for libraries that require specific traits to be implemented for types? I feel like it'd be pretty useful in cases like `actix-web`, which requires specific traits to be implemented like `ResponseError` so that errors can be converted into HTTP responses.

I feel like it'd be (at least a little) in line with the "You want it to be easy" user experience.

**Comment by dtolnay** [comment]
I am not interested in adding anything like that in this crate.
