### ISSUE TITLE
Use `std::backtrace::Backtrace` even on the stable channel

### ISSUE THREAD

**Issue by laralove143** [dtolnay/anyhow#284]
[Rust 1.65 has stabilized the backtrace API](https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html#stabilized-apis), so it should now be possible to use backtrace on the stable channel without anyhow's backtrace feature

**Comment by haraldreingruber-dedalus** [comment]
The sideffect is now that the feature macro can not be used on stable:

```
error[E0554]: `#![feature]` may not be used on the stable release channel                            
   --> C:\Users\...\.cargo\registry\src\github.com-1ecc6299db9ec823\anyhow-1.0.66\src\lib.rs:214:61
    |
214 | #![cfg_attr(backtrace, feature(error_generic_member_access, provide_any))]
```
