### ISSUE TITLE
Customize output format

### ISSUE THREAD

**Issue by fritzrehde** [dtolnay/anyhow#290]
Is there a way to customize the output format of anyhow errors that are printed to stdout? For example, this is how it formatted by default:
```
Error: Failed to read instrs from ./path/to/instrs.json

Caused by:
    No such file or directory (os error 2)
```

Could I somehow change this formatting to 
```
My custom error prefix: Failed to read instrs from ./path/to/instrs.json
Caused by: No such file or directory (os error 2)
```
or similar?

**Comment by dtolnay** [comment]
There is an example of custom formatting near the bottom of https://docs.rs/anyhow/1.0.69/anyhow/struct.Error.html#display-representations.
