### ISSUE TITLE
Related errors

### ISSUE THREAD

**Issue by andrewbaxter** [dtolnay/anyhow#292]
First of all, thanks for this library! It's super helpful.

Sometimes when handling an error another error occurs (during cleanup, rollback, etc) and I want to return both.  I want to keep any such errors that happen like that together in an error tree.

I think anyhow currently only supports a linear chain, but I'd like to request a method for doing this sort of "and also" error association.

**Comment by dtolnay** [comment]
I would prefer not to build this into this library. But it sounds useful for someone to explore in a different library.
