### ISSUE TITLE
Result<...> Deserialize error

### ISSUE THREAD

**Issue by Virgil-N** [dtolnay/anyhow#296]
```rust
#[derive(Debug, Serialize)]
pub struct HTTPResponse<T: for<'a> Deserialize<'a>> {
    pub code: u32,
    pub status: String,
    pub data: T,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Article {
    pub title: String,
    pub content: String,
    pub author: String,
    pub creat_time: String,
    pub categories: Vec<String>,
}

pub fn getNews(url: &str) -> Result<HTTPResponse<Article>> {
    let url = Url::parse(url).unwrap();
    let client = reqwest::blocking::Client::new();
    let response = client.get(url).send()?;

    response.json()? // error here

}
```

error:
the trait bound `anyhow::Error: Deserialize<'_>` is not satisfied
the following other types implement trait `Deserialize<'de>`:
  &'a Path
  &'a [u8]
  &'a str
  ()
  (T0, T1)
  (T0, T1, T2)
  (T0, T1, T2, T3)
  (T0, T1, T2, T3, T4)
and 139 others
required for `Result<HTTPResponse<Article>, anyhow::Error>` to implement `for<'de> Deserialize<'de>`
required for `Result<HTTPResponse<Article>, anyhow::Error>` to implement `DeserializeOwned`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B1%5D?1#file%3A%2F%2F%2FUsers%2Fvirgil%2Fworkspace%2Fpersonal%2Frust%2Ficed%2Ficed_viewer%2Fsrc%2Fapi.rs)
response.rs(240, 20): required by a bound in `reqwest::blocking::Response::json`

---
How to fix this?

**Comment by dtolnay** [comment]
Please take your question to any of the resources shown in https://www.rust-lang.org/community. This library and serde are both one of the most widely used Rust libraries and plenty of people will be able to provide guidance about them.
