### ISSUE TITLE
Add `core-error` feature to allow semantic use of `anyhow` in no_std

### ISSUE THREAD

**Issue by semiviral** [dtolnay/anyhow#304]
As the title says, it would be quite convenient if there were a feature-gate that allowed `anyhow` to take advantage of the recent `error_in_core` nightly feature. This would simplify using `anyhow` in no_std environments.

**Comment by dtolnay** [comment]
I am not interested in making use of the nightly feature, but once there is something usable from stable then this crate will use it.
