### ISSUE TITLE
Add `to_anyhow()` Result method.

### ISSUE THREAD

**Issue by zarik5** [dtolnay/anyhow#312]
Sorry if this was asked before, but I couldn't find this mentioned anywhere else. I found myself needing a method to convert errors to anyhow without bailing on `Err`. For this purpose I made a new trait:

```rust
pub trait ToAnyhow<T> {
    fn to_anyhow(self) -> Result<T>;
}

impl<T, E: Error + Send + Sync + 'static> ToAnyhow <T> for Result<T, E> {
    fn to_anyhow(self) -> Result<T> {
        match self {
            Ok(value) => Ok(value),
            Err(e) => Err(e.into()),
        }
    }
}
```

This is also easily achievable using `.map_err(|e| e.into())`, but I believe this should be a first class feature. Was this considered before?

**Comment by dtolnay** [comment]
I am happy with this being written `.map_err(anyhow::Error::from)`.

**Comment by Chaoses-Ib** [comment]
Could this be reconsidered? A quick search shows many crates are inventing their own trait for this:

![image](https://github.com/user-attachments/assets/0376f5e2-5837-4f25-b1ff-4b9dccba88f2)

![image](https://github.com/user-attachments/assets/fdb2333f-c71b-45b1-8649-d341603385c3)
