### ISSUE TITLE
backtrace seems to only work with opt-level=0

### ISSUE THREAD

**Issue by kurtbuilds** [dtolnay/anyhow#315]
This probably isn't a bug, but trying to understand how to use the library better.

In short, when I turn on `backtrace` feature, and build in dev, I get backtraces. However, running the same executable in release mode has the backtrace just return `"unsupported backtrace"`. After a lot of debugging, I identified `opt-level` as the culprit. If I set it to zero, I get backtraces. They disappear even going to level=1.

See this repo for a minimum example: https://github.com/kurtbuilds/playground.git

In `Cargo.toml`, commenting in/out `opt-level` config changes the behavior.

I'm quite confused by this, since sources online say that backtraces are just configured by having debug symbols (`debug = true`), the `RUST_BACKTRACE` environ variable, and the `backtrace` feature in anyhow.

---

Is it by design that `backtrace` only works with `opt-level=0`? At the very least, I'm surprised this behavior isn't better documented: I can't find anything - on Google, Rust std docs, or anyhow - that mentions `opt-level` impacting backtraces. Are there plans to change this behavior?

**Comment by dtolnay** [comment]
I ran `RUST_LIB_BACKTRACE=1 cargo run --release` in your repo at https://github.com/kurtbuilds/playground/commit/64b7026698fbd00c8f3d665715e18b33f403c1f5 and I get a backtrace.

```console
   0: anyhow::error::<impl anyhow::Error>::msg
             at /home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.72/src/error.rs:83:36
   1: playground::foo
             at ./src/main.rs:4:16
   2: playground::main
             at ./src/main.rs:8:13
   3: core::ops::function::FnOnce::call_once
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/core/src/ops/function.rs:250:5
   4: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/sys_common/backtrace.rs:135:18
   5: std::rt::lang_start::{{closure}}
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/rt.rs:166:18
   6: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/core/src/ops/function.rs:284:13
   7: std::panicking::try::do_call
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/panicking.rs:524:40
   8: std::panicking::try
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/panicking.rs:488:19
   9: std::panic::catch_unwind
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/panic.rs:142:14
  10: std::rt::lang_start_internal::{{closure}}
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/rt.rs:148:48
  11: std::panicking::try::do_call
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/panicking.rs:524:40
  12: std::panicking::try
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/panicking.rs:488:19
  13: std::panic::catch_unwind
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/panic.rs:142:14
  14: std::rt::lang_start_internal
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/rt.rs:148:20
  15: main
  16: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  17: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  18: _start
```

```console
rustc 1.73.0-nightly (32303b219 2023-07-29)
binary: rustc
commit-hash: 32303b219d4dffa447aa606bc11c7a648f44a862
commit-date: 2023-07-29
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
```

**Comment by thomcc** [comment]
I can't reproduce this on macOS with nightly or stable, release or debug.

**Comment by thomcc** [comment]
That said backtraces on macOS are a bit weird, we don't 100% support them, see <https://github.com/rust-lang/backtrace-rs/blob/0533d475a52389ea0612b5543316bb571afc30ac/src/backtrace/libunwind.rs#L58-L72> So maybe this is related to that.

**Comment by kurtbuilds** [comment]
I realized I was getting different behavior because I was using a different linker. Closing this, and thank you for help digging into this.
