### ISSUE TITLE
`ensure!` shown in the docs is different than actual definition

### ISSUE THREAD

**Issue by gimbles** [dtolnay/anyhow#325]
The `ensure!` macro has a completely different definition in the documentation, and what is actually used in the library.

https://docs.rs/anyhow/latest/src/anyhow/macros.rs.html#120-143

![image](https://github.com/dtolnay/anyhow/assets/93856041/32b32682-e54c-4956-b0c3-0001e9e894ec)

The documentation macro definition is
```rs
macro_rules! [ensure](https://docs.rs/anyhow/latest/anyhow/macro.ensure.html) {
    ($cond:expr $(,)?) => {
        if !$cond {
            return $crate::__private::Err($crate::Error::msg(
                $crate::__private::concat!("Condition failed: `", $crate::__private::stringify!($cond), "`")
            ));
        }
    };
    ($cond:expr, $msg:literal $(,)?) => {
        if !$cond {
            return $crate::__private::Err($crate::__anyhow!($msg));
        }
    };
    ($cond:expr, $err:expr $(,)?) => {
        if !$cond {
            return $crate::__private::Err($crate::__anyhow!($err));
        }
    };
    ($cond:expr, $fmt:expr, $($arg:tt)*) => {
        if !$cond {
            return $crate::__private::Err($crate::__anyhow!($fmt, $($arg)*));
        }
    };
}
```

(A pretty good implementation, generally what a rustacean would expect!)

But the macro which is actually used while compiling code is completely different
```rs
macro_rules! ensure {
    ($($tt:tt)*) => {
        $crate::__parse_ensure!(
            /* state */ 0
            /* stack */ ()
            /* bail */ ($($tt)*)
            /* fuel */ (~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~~)
            /* parse */ {()}
            /* dup */ ($($tt)*)
            /* rest */ $($tt)*
        )
    };
}
```

# The problems with this

- The docs are *completely* misleading on what the macro actually is
The macro shown in the documentation is not what the macro used in code is
- The `__parse_ensure!` macro is nearly 800 lines of code
Was the parse_ensure macro necessary here? Rather, is it necessary at all? It is completely undocumented as far as I can find, and it looks far more than what is required.
- Were the compile time influence not considered during this at all?
Evaluating that macro would take a *lot* of time. It's massive

*Why* even have different implementations in the docs and in the implementation? The documentation implementation doesn't even look wrong, and should do the same thing (while being a much simpler, faster to compile macro).

Other crates such as [`eyre`](https://docs.rs/eyre) also have a similar, simpler implementation of the `ensure` macro https://docs.rs/eyre/latest/src/eyre/macros.rs.html#109-125

**Comment by conradludgate** [comment]
The `__parse_ensure` macro is used to allow the following error messages:

```rust
let (x, y) = (5, 6);
anyhow::ensure!(x == y);
```

into

```
Error: Condition failed: `x == y` (5 vs 6)
```

An example output of the macro

```rust
match (&x, &y) {
    (lhs, rhs) => {
        if !(lhs == rhs) {
            #[allow(unused_imports)]
            use ::anyhow::__private::{BothDebug, NotBothDebug};
            return Err((lhs, rhs).__dispatch_ensure("Condition failed: `x == y`"));
        }
    }
}
```

It is complicated but necessary for these nicer error messages.

**Comment by gimbles** [comment]
Sure, this is valid. But the documentation is still misleading. (Especially since clicking `source` leads to the wrong definition) and could the implementation of this not have been simpler?

**Comment by Nilstrieb** [comment]
It's not really misleading, it's documentation on how to use the macro. The actual implementation would generate very useless documentation that would not serve the job of documentation- describing on the macro can be used.

**Comment by gimbles** [comment]
Sure, that can be in the docs itself though, rather than pointing to a completely different macro entirely.

**Comment by gimbles** [comment]
The current solution is not very accurate either, look at the expansion of this:
```rs
use anyhow::ensure;

ensure!(true == true || false == true);
```

```rs
use anyhow::ensure;

if !(true == true || false == true) {
    return ::anyhow::__private::Err(::anyhow::Error::msg(
        "Condition failed: `true == true || false == true`",
    ));
};
```

It doesn't detect the `==` operation occurring and add the specialized diagnostic. (The condition is parsed as `true == (true || (false == true))`)

A proc macro for this should be much better, imo. It would both more accurately perform this and should hopefully be faster than the decl macro implementation right now. 🤷🏽‍♀️

**Comment by dtolnay** [comment]
https://github.com/dtolnay/anyhow/issues/325#issuecomment-1782882042 is accurate about why it's set up this way. The input patterns shown are indeed the 4 patterns that the macro accepts. The real macro implementation just parses the same things token-by-token instead of through macro_rules's built-in $:expr parser.

**Comment by gimbles** [comment]
Sure. But the "source" of the macro according to the docs is still completely misleading. 
When I click "source" on the docs, there's no comment or no indication at all (neither in the docs themselves nor in any comment in the source code) to the actual implementation of the macro. It just points to a pseudo-macro.
If I hadn't noticed the tiny cfgs, I would've been completely oblivious to this too.

This is still ignoring
- The compile time affect of this
- The accuracy of this (https://github.com/dtolnay/anyhow/issues/325#issuecomment-1783039224)

Hacking together a semi-parser of Rust code in a declarative macro seems unnecessary and a misuse of them. A proc-macro seems much better suited here?

**Comment by gimbles** [comment]
If the point of the cfg(docs) macro is to simply be a place holder for the docs, why implement at _all?_
