### ISSUE TITLE
Default Ok-type to `()` in `anyhow::Result` typedef

### ISSUE THREAD

**Issue by emilk** [dtolnay/anyhow#344]
WARNING: This issues is a matter of style and taste! :)

I have a lot of `anyhow::Result<()>` in my code base. I find it ugly.

If we change the definition of `anyhow::Result` from

```rust
pub type Result<T, E = Error> = core::result::Result<T, E>;
```

to

```rust
pub type Result<T = (), E = Error> = core::result::Result<T, E>;
```

Then we could rewrite

```rust
fn foo() -> anyhow::Result<()> {
    …
}
```

to

```rust
fn foo() -> anyhow::Result {
    …
}
```

This would NOT be a breaking change (afaict).

**Comment by dtolnay** [comment]
I would prefer not to make this change.

You can write your own Result type alias in your crate.

**Comment by emilk** [comment]
Fair enough!
