### ISSUE TITLE
Depending on `CARGO_ENCODED_RUSTFLAGS` may produce stale builds

### ISSUE THREAD

**Issue by workingjubilee** [dtolnay/anyhow#349]
q.v.
- https://github.com/rust-lang/cargo/issues/13003
- https://github.com/dtolnay/anyhow/issues/323
- https://github.com/rust-lang/rust/issues/120804

**Comment by dtolnay** [comment]
This was fixed in Cargo by https://github.com/rust-lang/cargo/pull/13560 + https://github.com/rust-lang/rust/pull/123745.
