### ISSUE TITLE
`anyhow::ensure!` doesn't work with custom error type

### ISSUE THREAD

**Issue by samuela** [dtolnay/anyhow#361]
I'm struggling to get `anyhow::ensure!` to cooperate with my custom error type. (Using a custom error type is [necessary for compatibility with axum](https://github.com/tokio-rs/axum/blob/main/examples/anyhow-error-response/src/main.rs) in my case.)

Here's what I've got:
```rs
use anyhow; // 1.0.81

#[derive(Debug)]
struct AppError(anyhow::Error);
type AppResult<T> = Result<T, AppError>;

impl<E> From<E> for AppError
where
  E: Into<anyhow::Error>,
{
  fn from(err: E) -> Self {
    Self(err.into())
  }
}

fn foo() -> AppResult<()> {
    // expected `AppError`, found `Error`
    anyhow::ensure!(false, "expected true");
    Ok(())
}

// fn foo() -> AppResult<()> {
//     // This SO post (https://stackoverflow.com/questions/67656431/simplier-way-to-return-custom-error-type-with-anyhowerror)
//     // suggests that this ought to work, but it doesn't.
//     anyhow::ensure!(false, AppError(anyhow::anyhow!("expected true")));
//     Ok(())
// }
```

How does one use a custom error type with `anyhow::ensure!`?

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4b8139138ce157933f5571ccb2f01f10)

**Comment by yyny** [comment]
See #112.
