### ISSUE TITLE
Consider providing format_err! as an alias for anyhow!

### ISSUE THREAD

**Issue by joshtriplett** [dtolnay/anyhow#37]
The `anyhow` crate works very well as a drop-in substitute for `failure`. One notable API difference: the `anyhow` crate uses `anyhow!` instead of `format_err!`. `format_err!` seems like a more self-explanatory and generic name, and one more suited to #13 in the future as well. Would you consider providing `format_err!` as an equivalent to `anyhow!`?

**Comment by dtolnay** [comment]
Sure thing, I agree that's likely the name this would be given if it were going into std.

**Comment by dtolnay** [comment]
Added in 1.0.19.

**Comment by joshtriplett** [comment]
Thanks!
