### ISSUE TITLE
Cannot compile when using `ensure!`

### ISSUE THREAD

**Issue by photino** [dtolnay/anyhow#372]
When I upgrade `anyhow` to `1.0.85`, it fails to compile our project [zino](https://github.com/zino-rs/zino).

After some struggles, I find that the latest change of `ensure` fails to compile the following code:
```rust
fn main() -> anyhow::Result<()> {
    let a = 5;
    let b = 3;
    // Can compile
    anyhow::ensure!(a <= b || (a - b) <= 10, "always true");
    // Cannot compile
    anyhow::ensure!(a <= b || a - b <= 10, "always true");
    Ok(())
}
```

**Comment by dtolnay** [comment]
Sorry about the breakage. I have published a fix in 1.0.86.
