### ISSUE TITLE
Prettier error printing

### ISSUE THREAD

**Issue by arzg** [dtolnay/anyhow#40]
When printing anyhow’s Result type (e.g. on return from `fn main`) the error is formatted as `Error: xyz`. I was wondering if it is possible to customise this formatting. Additionally, Clap has its own error formatting it uses for argument parsing errors and the like. Is it somehow possible to make error printing consistent across Clap and anyhow, and perhaps other crates too?

Thanks.

**Comment by dtolnay** [comment]
Yes, you can customize the formatting.

```rust
use anyhow::{Context, Result};

fn main() {
    if let Err(err) = try_main() {
        println!("ERROR: {}", err);
        err.chain().skip(1).for_each(|cause| println!("because: {}", cause));
        std::process::exit(1);
    }
}

fn try_main() -> Result<()> {
    std::fs::read("/nonexist").context("failed to read nonexistent file")?;
    Ok(())
}
```

**Comment by arzg** [comment]
Ah, thanks for the info.

**Comment by zicklag** [comment]
This would be a great example to have in the docs or the README.

**Comment by dtolnay** [comment]
Added an example of custom formatting to https://docs.rs/anyhow/1.0.20/anyhow/struct.Error.html#display-representations.
