### ISSUE TITLE
reversed printing

### ISSUE THREAD

**Issue by burrbull** [dtolnay/anyhow#43]
When context is present, it prints in reverse order
```
ERROR svd2rust: In peripheral `PLIC`  <-- this is context

Caused by:
    0: In cluster `targets[%s]`
    1: In register `threshold`
    2: Parsing field #0
    3: In field `priority`
    4: Expected content in <enumeratedValues> tag, found none    <-- this is error
```

**Comment by dtolnay** [comment]
Could you show exactly what you would want this chain of errors to be printed as?

**Comment by burrbull** [comment]
In this example error, lowest level is (4) https://github.com/rust-embedded/svd/blob/27beb89c3eef5fbc8640b1655444a92be2888aa4/src/error.rs#L16 and I think it should be printed by `Display`
All other strings were added by `with_context`.
`In peripheral PLIC` - highest level of context.

Although I may be wrong.

**Comment by burrbull** [comment]
If it is generally accepted I close issue.

**Comment by dtolnay** [comment]
I think this is behaving correctly. For example in standard library errors you can see the lowest level underlying error is *not* what is printed as the main representation:

```rust
use std::ffi::CString;
use std::error::Error;

fn main() {
    let cstring = CString::new(vec![255]).unwrap();
    let error = cstring.into_string().unwrap_err();
    println!("DISPLAY: {}", error);
    println!("CAUSE: {}", error.source().unwrap());
}
```

```console
DISPLAY: C string contained non-utf8 bytes
CAUSE: invalid utf-8 sequence of 1 bytes from index 0
```

The lowest level error is "invalid utf-8 sequence of 1 bytes from index 0" while the context is "C string contained non-utf8 bytes".

If you want the cause chain printed in the opposite order, you can try printing it yourself:

```rust
use anyhow::anyhow;

fn main() {
    let err = anyhow!("Expected content in <enumeratedValues> tag, found none")
        .context("In field `priority`")
        .context("Parsing field #0")
        .context("In register `threshold`")
        .context("In cluster `targets[%s]`")
        .context("In peripheral `PLIC`");
    for err in err.chain().collect::<Vec<_>>().iter().rev() {
        println!("{}", err);
    }
}
```

But I would recommend instead phrasing your contexts to make it more clear what failed:

```console
Error: Invalid data for peripheral `PLIC` in STM32F30x.svd

Caused by:
    0: Failed to load cluster `targets[%s]` from svd
    1: Failed to load register `threshold` from svd
    2: Failed to parse field #0 of register
    3: Invalid value for field `priority`
    4: Expected content in <enumeratedValues> tag, found none
```

**Comment by burrbull** [comment]
> I think this is behaving correctly. For example in standard library errors you can see the lowest level underlying error is _not_ what is printed as the main representation:

Thank you for explanation.
