### ISSUE TITLE
How to combine this with io::Error?

### ISSUE THREAD

**Issue by svenstaro** [dtolnay/anyhow#56]
So I'm using actix-web 2 and would like to do something like this:
```rust
use anyhow::Result;

#[actix_rt::main]
async fn main() -> Result<()> {
    HttpServer::new(|| App::new().bind("0.0.0.0:8080"))?.run().await
}
```

but that doesn't work as anyhow's Result is incompatible and doesn't offer any conversion methods that I can see to be interoperable with io::Result.

What would be a good way to resolve this? I'd generally like to use anyhow here but because `anyhow::Result` can't be implicitly converted from a `io::Result` there is no ergonomic way I see here.

**Comment by svenstaro** [comment]
Disregard this. Turns out I was misusing this.

**Comment by tversteeg** [comment]
What ended up being your solution for this?

**Comment by svenstaro** [comment]
Essentially this:

```rust
    HttpServer::new(|| App::new().bind("0.0.0.0:8080"))?.run().await.context("Error while running web server!")
```

**Comment by dtolnay** [comment]
`?` would be the usual way to convert an error type.

```rust
HttpServer::new(...).bind("0.0.0.0:8080")?.run().await?;
Ok(())
```

It looks like @svenstaro's code in https://github.com/dtolnay/anyhow/issues/56#issue-544971250 was already using this for the io error from `bind`.
