### ISSUE TITLE
Is non-recursive downcasting supported?

### ISSUE THREAD

**Issue by alexcrichton** [dtolnay/anyhow#57]
This is mostly a question but may also be a feature request, I'm not sure! I tried to give migrating Cargo itself from `failure` to `anyhow` a spin today. Compiler-wise the transition was quite easy but the tests are turning up some nasty issues that are taking some time to debug! One of them here is related to the behavior  [documented here](https://docs.rs/anyhow/1.0.26/anyhow/trait.Context.html#effect-on-downcasting).

In `failure` I believe `downcast_ref` only attempted the downcast on the single error itself with no recursion, so Cargo ended up accidentally relying on that behavior. It looks like `anyhow` is working differently though. 

Cargo has a few use cases which are actually expressed a bit more succinctly with the recursive behavior (such as [seeing if a spurious network failure happened](https://github.com/rust-lang/cargo/blob/7059559d71de3fffe8c8cb81e32f323454aa96c5/src/cargo/util/network.rs#L39-L66), which no longer needs to loop).

A current use case of Cargo, however, relies on *not* recursively downcasting. Cargo has a (in retrospect weird) convention where given a chain of errors it may only print some of them instead of all of them. The intention is that `cargo build` prints only what you need with an error, while `cargo build --verbose` will always print the entire error. A good example of this is that `cargo build` will not print out the full error if rustc itself fails (e.g. a compiler error), but `cargo build --verbose` will print out the full compiler invocation command line. 

Today Cargo uses a "marker error" called [`Internal`](https://github.com/rust-lang/cargo/blob/7059559d71de3fffe8c8cb81e32f323454aa96c5/src/cargo/util/errors.rs#L50-L76) which is just a type-level marker indicating "this error and below are only printed in `--verbose` mode".

There's a few places in Cargo that attempt to check for this when iterating through the chain of errors, but the behavior change with `anyhow` is what's causing issues now. For example:

* Using `downcast_ref` on a top-level error returns if *any* sub-`Error` came from an `Internal`
* Trying to print everything leading up to the `Internal` means that if there's any `Internal` none of them get printed.

Does `anyhow` support a use case like the `Internal` idea? Is there a way to downcast, but not recursively, so to act on differences in the error causal chain?

**Comment by dtolnay** [comment]
Yes -- if you deref first to &std::error::Error then you get the standard library's downcast implementation which is nonrecursive.

```rust
use anyhow::{anyhow, Error};
use std::fmt::{self, Debug, Display};

pub struct Internal(Error);

impl std::error::Error for Internal {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.0.source()
    }
}

impl Debug for Internal {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        Debug::fmt(&self.0, f)
    }
}

impl Display for Internal {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        Display::fmt(&self.0, f)
    }
}

fn main() {
    let e0 = anyhow!("e0");
    let e1 = e0.context("e1");
    let e2 = e1.context("e2");
    let e2_internal = anyhow!(Internal(e2));
    let e3 = e2_internal.context("e3");
    let e4 = e3.context("e4");

    println!("recursive downcast: {}", e4.downcast_ref::<Internal>().is_some());
    println!("nonrecursive downcast: {}", (&*e4).downcast_ref::<Internal>().is_some());

    for e in e4.chain() {
        println!("{} {}", e, e.downcast_ref::<Internal>().is_some());
    }
}
```

```console
recursive downcast: true
nonrecursive downcast: false
e4 false
e3 false
e2 true
e1 false
e0 false
```

**Comment by alexcrichton** [comment]
Oh for some reason I thought that the standard library implementation would have the same behavior via an override, but I see now that's not even possible much less not even the case! Thanks!
