### ISSUE TITLE
`downcast_ref` on `anyhow::Error` vs `&dyn std::error::Error`

### ISSUE THREAD

**Issue by idubrov** [dtolnay/anyhow#58]
We are looking into migrating from `failure` crate to a combination of `thiserror`+`anyhow`. The way we have our error handling set up is that we can go through the chain of errors and "cross-cast" them into a trait object of our own (say, `&dyn ExtraInfo`).

The way this is done is through a registry of "casting" functions which would cast to a specific type `T: ExtraInfo`, then coerce to `&dyn ExtraInfo`.

One use-case we need to support is to allow this mechanism to work with "contexts" (we might not need this use-case anymore since `anyhow::Error` could be embedded as a `#[source]` into structured errors). For `failure` case, we do that by "registering" downcasting functions twice: once for type `T` and once for `Context<T>`.

However, `anyhow` does not expose "context" type. On the other hand, it seems to support downcasting to type inside the "context error" directly via `downcast_ref` on the `&anyhow::Error`. But for some reason (I mean... given the internals of `anyhow::Error` it is not surprising -- it's quite sophisticated piece of machinery!), it doesn't work when done via `&dyn std::error::Error`. Test case: 

```rust
#[derive(Debug, thiserror::Error, PartialEq)]
#[error("some error")]
struct SomeError(usize);

fn main() {
    let error = anyhow::Error::msg("error");
    let error = error.context(SomeError(123));
    // Works 😅
    assert_eq!(error.downcast_ref::<SomeError>().unwrap(), &SomeError(123));
    let error: &dyn std::error::Error = &*error;
    // Fails 😞
    assert_eq!(error.downcast_ref::<SomeError>().unwrap(), &SomeError(123));
}
```

**Comment by dtolnay** [comment]
If you need the previous approach of downcasting to Context\<C\> to work, it should be possible to define your own extension trait which you use instead of anyhow::Context:

```rust
pub struct Context<C> {
    context: C,
    source: Error,
}

pub trait DowncastableContext {
    type Ok;

    fn context<C>(self, context: C) -> Result<Self::Ok, Error>
    where
        C: Display + Send + Sync + 'static; // same signature as anyhow::Context
}

impl<T, E> DowncastableContext for Result<T, E>
where
    E: Into<Error>,
{
    type Ok = T;

    fn context<C>(self, context: C) -> Result<Self::Ok, Error>
    where
        C: Display + Send + Sync + 'static,
    {
        self.map_err(|err| {
            let source = err.into();
            Error::new(Context { context, source })
        })
    }
}
```

**Comment by idubrov** [comment]
Right, we can do that, basically have our own "context" errors.

But why is there a difference in downcasting behavior? At very least, it looks confusing to me. Is it documented anywhere?

**Comment by dtolnay** [comment]
It's intentionally different from the simplistic downcasting that std::error::Error comes with.

Notice that the signatures are not even the same, https://doc.rust-lang.org/std/error/trait.Error.html#method.downcast_ref is `fn downcast_ref<T: Error + 'static>` while https://docs.rs/anyhow/1.0/anyhow/struct.Error.html#method.downcast_ref is `fn downcast_ref<E: Display + Debug + Send + Sync + 'static>`, since the caller's context types generally would not have a std Error impl.

**Comment by idubrov** [comment]
Thanks, makes total sense. I just find it a bit confusing.
