### ISSUE TITLE
Providing newtype macro

### ISSUE THREAD

**Issue by Kixunil** [dtolnay/anyhow#59]
This is a very useful crate for prototyping, even libraries, but library authors often like to provide advanced features like getting error kind or structured context. However, in early phase of library development, these extra features might be a burden.

A nice way to resolve it is to have a newtype encapsulating `anyhow::Error`, which can be changed at any time. One most likely wants to forward `fmt::Debug` and `fmt::Display` traits. This requires boilerplate, though.

I propose adding a `newtype!($name:ident) => { pub struct $name(anyhow::Error); ... }` macro which generates such newtype and delegates the relevant traits to it. Alternatively, it could be attribute-like proc macro on unit structs, allowing to add derives and control visibility.

**Comment by dtolnay** [comment]
Users should use https://github.com/dtolnay/thiserror if they want to define their own errors as newtype structs.

```rust
#[derive(Error, Debug)]
#[error(transparent)]
pub struct MyError(anyhow::Error);
```

**Comment by Kixunil** [comment]
Damn, I missed it. Thanks!
