### ISSUE TITLE
Context defined for Option<T>?

### ISSUE THREAD

**Issue by stevedonovan** [dtolnay/anyhow#6]
Is there any appetite for implementing `context` and `with_context` for optional values? Our homegrown lib does this and we have become addicted to the convenience.  (But we will outgrow homegrown ...)

I can do a PR if there's interest.....

**Comment by dtolnay** [comment]
Seems reasonable to me. Something like this? #8

**Comment by stevedonovan** [comment]
Great, that would do nicely. I remember there was a similar debate in the Failure issues, and the decision went the other way.
