### ISSUE TITLE
A more ergonomic way for adding context that needs formatting

### ISSUE THREAD

**Issue by thomaseizinger** [dtolnay/anyhow#60]
Currently, one has to use `with_context` to pass a string that is built out of several components:

```rust
function_returning_result()
   .with_context(|| format!("failed to fetch something with id {}", id))?
```

It would be a nice ergonomic improvement, if we could do:

```rust
function_returning_result()
   .context("failed to fetch something with id {}", id)?
```

I am unaware of a way in Rust to do functions with variadic arguments but something that should be possible is:

```rust
function_returning_result()
   .context(format_args!("failed to fetch something with id {}", id))?
```

`format_args!` avoids heap-allocations, hence it should be fine to invoke this outside of a closure.

Thoughts?
Likely there are even better ways of doing that.

My main usecase is passing a string to `context` that includes arguments from the current scope.

**Comment by dtolnay** [comment]
I think I am going to stick with the current signature of Context which requires the context argument to be Send + Sync + 'static which fmt::Arguments is not, but one thing you could do is define your own context trait to lazily to_string an argument of type fmt::Arguments. Something like:

```rust
use anyhow::{anyhow, Error, Result};
use std::fmt;

trait LazyContext<T, E> {
    fn context(self, args: fmt::Arguments) -> Result<T, Error>;
}

impl<T, E> LazyContext<T, E> for Result<T, E>
where
    Self: anyhow::Context<T, E>,
{
    fn context(self, args: fmt::Arguments) -> Result<T, Error> {
        match self {
            Ok(ok) => Ok(ok),
            Err(_) => anyhow::Context::context(self, args.to_string()),
        }
    }
}

fn main() -> Result<()> {
    fn f(_: usize) -> Result<()> { Err(anyhow!("something wrong")) }

    let id = 0;
    f(id).context(format_args!("failed to fetch id {}", id))?;
    Ok(())
}
```

Or possibly the same thing generalized to `fn context(self, args: impl Display) -> Result<T, Error>`.
