### ISSUE TITLE
[i18n] How to translate the default anyhow messages?

### ISSUE THREAD

**Issue by silvioprog** [dtolnay/anyhow#64]
Hi.

I have a small application using `anyhow` which can raise errors like this:

```
Error: Não foi possível ler arquivo 'algum-arquivo.txt'

Caused by:
    No such file or directory (os error 2)
```

however, it would be nice to show the following translation to our users:

```
Oops, ocorreu um erro: Não foi possível ler arquivo 'algum-arquivo.txt'

Causa do erro:
    No such file or directory (os error 2)
```

So, is there any option to translate it dynamically without changing the original `anyhow` sources?

TIA for any help!

**Comment by dtolnay** [comment]
Yes, your application can render the errors itself. Check out where it shows `try_main` near the bottom of https://docs.rs/anyhow/1.0.26/anyhow/struct.Error.html. You can do something like that but with indentation to match the default output.

**Comment by silvioprog** [comment]
**SOLVED!** :+1: This worked like a charm as suggested:

```rust
    let webservices = match WebServices::from_file(&webservices).with_context(|| {
        format!(
            "Não foi possível ler arquivo de webservices '{}'",
            webservices
        )
    }) {
        Ok(webservices) => webservices,
        Err(err) => {
            eprintln!("Oops, ocorreu um erro: {}", err);
            err.chain()
                .skip(1)
                .for_each(|cause| eprintln!("Causa do erro: {}", cause));
            std::process::exit(1);
        }
    };
```

Thank you very much for helping and for this awesome library! :smiley:
