### ISSUE TITLE
? does not coerce Box<dyn Error + Send + Sync + 'static> to anyhow::Error

### ISSUE THREAD

**Issue by That3Percent** [dtolnay/anyhow#66]
It is common in crates that take the anyhow approach of loosely typed dynamic error types to return `Result<T, Box<dyn Error + Send + Sync + 'static>>`.

Like anyhow, this type is convenient to use - automatically coercing from `impl Error` and even `String`.

But, when trying to interop with this common return value using `?` the compiler stumbles with:

> the trait `std::marker::Sized` is not implemented for `dyn std::error::Error + std::marker::Send + std::marker::Sync`

Here is a minimum reproducible case:
```rust
use anyhow;

fn dyn_error() -> Result<(), Box<dyn std::error::Error + Send + Sync + 'static>> {
    Ok(())
}

fn anyhow_error() -> Result<(), anyhow::Error> {
    dyn_error()?;
    Ok(())
}
```

**Comment by dtolnay** [comment]
I don't think this is something that could be fixed in anyhow. There is a missing impl of std::error::Error for Box\<dyn Error\> in std -- https://github.com/rust-lang/rust/issues/60759. Once specialization is mature enough that the missing impl can be provided in std, it will fix this issue.
