### ISSUE TITLE
Error do not implement Serialize Deserialize

### ISSUE THREAD

**Issue by Fi3** [dtolnay/anyhow#67]
Hi, I need to put a `anyhow::Result` in a struct that derive the traits `serde::Serialize` and `serde::Desrilize` but `anyhow::Error` do not implement these traits so is impossible to derive them in my struct.

There is a way around? These traits will ever be implemented?

**Comment by dtolnay** [comment]
For your use case, could you share how you would expect anyhow::Error to be represented from serde's perspective? For example what would be your expectation for what the following program should print?:

```rust
fn main() {
    let io_e = std::io::Error::new(std::io::ErrorKind::Other, "...");
    let any_e = anyhow::Error::from(io_e);
    println!("{}", serde_json::to_string(&any_e).unwrap());
}
```
