### ISSUE TITLE
impl From<NoneError> for anyhow::Error

### ISSUE THREAD

**Issue by repnop** [dtolnay/anyhow#74]
As `NoneError` doesn't impl `std::error::Error` at this moment in time, would it be reasonable to add a `From` impl for it to `anyhow::Error` in some fashion?

**Comment by dtolnay** [comment]
This impl wouldn't be allowed in `anyhow` by coherence, so we can't add this.

**Comment by repnop** [comment]
Ah, forgot about that. Thanks for the quick response :)

**Comment by WyseNynja** [comment]
So if we can't use a From, what is the standard way to deal with an error like NoneError?

**Comment by WyseNynja** [comment]
Never mind! I think this is the common way: https://github.com/dtolnay/anyhow/issues/35#issuecomment-547986739

**Comment by trevyn** [comment]
More concise way, that was non-obvious to me:
```rust
use anyhow::{Context, Result};

fn maybe_get() -> Option<T> {
    ...
}

fn demo() -> Result<()> {
    let t = maybe_get().context("there is no T")?;
    ...
}
```

from https://docs.rs/anyhow/1.0.31/anyhow/trait.Context.html#impl-Context%3CT%2C%20Infallible%3E-for-Option%3CT%3E

**Comment by jkelleyrtp** [comment]
Context is waaay better than what I've been using. Thanks!

```rust
 .ok_or(anyhow!("there is no T"));
```
