### ISSUE TITLE
Feature idea: a macro to add context to a function

### ISSUE THREAD

**Issue by andrewhickman** [dtolnay/anyhow#76]
I find myself often writing code like
```
fn parse_config(path: &Path) -> anyhow::Result<Config> {
    let file = BufReader::new(File::open(path)?);
    let config = serde_json::from_reader(file)?;
    Ok(config)
}
```
And then using it like `parse_config(path).context("failed to parse config")`. The issue is the `.context` bit has to be repeated for every call. The alternative is to put it inside the `parse_config` function, but this requires either repeating it at each `?` site, or creating a inner helper function
```
fn parse_config(path: &Path) -> anyhow::Result<Config> {
    fn inner(path: &Path) {
        let file = BufReader::new(File::open(path)?);
        let config = serde_json::from_reader(file)?;
        Ok(config)
    }
    inner(path).context("failed to parse config")
}
```
It would be nice to have a macro to do this for us
```
#[error_context("failed to parse config")]
fn parse_config(path: &Path) -> anyhow::Result<Config> {
    let file = BufReader::new(File::open(path)?);
    let config = serde_json::from_reader(file)?;
    Ok(config)
}
```
Thoughts? Should this be a part of `anyhow` or a seperate crate (I'm not aware of any crate for this currently)

**Comment by andrewhickman** [comment]
I've implemented a simple version of this [here](https://github.com/andrewhickman/fn-error-context).

**Comment by dtolnay** [comment]
I would prefer not to include a proc macro for this in anyhow, but people should feel free to use a separate crate if they prefer this style. https://github.com/yoshuawuyts/context-attribute provides an implementation that works with anyhow.
