### ISSUE TITLE
Newbie question: asserting errors in unit tests

### ISSUE THREAD

**Issue by bradwood** [dtolnay/anyhow#82]
Hi,

I'm trying to figure out a way of asserting a specific error (with a specific message) in a unit test.

Is there a recommended/idiomatic way of writing such a test.

Thanks
Brad

**Comment by dtolnay** [comment]
You should be able to assert a specific message like this:

```rust
assert_eq!(err.to_string(), "...");
```

If you also want to assert the type of the error, that would be:

```rust
assert_eq!(err.downcast_ref::<SpecificError>().unwrap().to_string(), "...");
```

**Comment by bradwood** [comment]
Great, thanks! That's pretty obvious now!! I was trying `err.kind()` which I think I've figured out won't work unless on a concrete error type.
