### ISSUE TITLE
Explicit constructor from Box<dyn Error + Send + Sync>

### ISSUE THREAD

**Issue by vorner** [dtolnay/anyhow#83]
Hello

I've noticed there's a (closed) issue about having a `From<Box<dyn Error + Send + Sync>>` impl, that refers to wanting that from `std` (#66)

But would it make sense to have an explicit constructor in the meantime? Eg. `Error::from_box_error(..)`? That way one would have to write some kind of `map_error(Error::from_box_error)?` instead of just `?`, but that's probably better than nothing.

**Comment by dtolnay** [comment]
`anyhow!` handles the conversion.

```rust
use anyhow::anyhow;

fn main() {
    let e: Box<dyn std::error::Error + Send + Sync> = unimplemented!();
    let e = anyhow!(e);
}
```

**Comment by vorner** [comment]
Reading the docs, doesn't this stringify the error? Won't it lose all the `source` chain, type information and such?

I'd hope it could somehow convert the existing `dyn Error` from 2-words trait object to the internal 1-word trait object. Or is it not possible?

**Comment by vorner** [comment]
Oh, I'm reading through the source code and it seems to be preserving it somehow. Would you mind if I send a PR making such usage clearer in the docs? Also, link from the `Error` type to the macro would make it little bit easier to find.

**Comment by rbtcollins** [comment]
Perhaps I'm missing something but anyhow! isn't very easy to use with `?`. 
```
fn main() -> anyhow::Result<()>{
   something_returning_boxed_error()?;
}
```

is a bit awkward - I mean:

```
fn main() -> anyhow::Result<()>{
  match something_returning_boxed_error(){
     Ok(v) => Ok(v),
     Err(e) => anyhow!(e)
  }?
}
```

**Comment by vorner** [comment]
It could be shorter with `map_err` instead of explicit match, eg something like:

```rust
something_returning_boxed_error().map_err(|e| anyhow!(e))?
```

This would be even slightly more ergonomic if it existed as a function/constructor/method, eg:

```rust
something_returning_boxed_error().map_err(Anyhow::from_boxed)
```

But as long as Rust doesn't allow implementing `impl From<Box<std::error::Error + Send + Sync>> for Anyhow`, this is probably the best that can be done :-(.

**Comment by DanielJoyce** [comment]
Looks like SNAFU crate handles this issue 

https://stackoverflow.com/questions/65151237/why-doesnt-boxdyn-error-implement-error
