### ISSUE TITLE
It doesn't print the whole chain, only the last context

### ISSUE THREAD

**Issue by Boscop** [dtolnay/anyhow#85]
According to [this](https://docs.rs/anyhow/1.0.28/anyhow/trait.Context.html#example), the `Display` impl prints the whole chain. But for me, `eprintln!("{}", e);` only prints the last added context, which is not helpful at all because even the underlying OS error is not printed.
It only prints the whole chain when I iterate manually:
```rust
		for e in e.chain() {
			eprintln!("{}", e);
		}
```
But this is just quick & dirty, it doesn't have the nice formatting (with "Caused by") and indentation as it should have according to the docs.

**Comment by dtolnay** [comment]
This is intentional. The ways to print other representations are shown in https://docs.rs/anyhow/1.0.28/anyhow/struct.Error.html#display-representations.

**Comment by Boscop** [comment]
@dtolnay But when I use `{:#}` it also only prints the last cause, not the whole chain. Why?
It says:
> To print causes as well using anyhow's default formatting of causes, use the alternate selector "{:#}".

So shouldn't it print all causes?

**Comment by DanielJoyce** [comment]
Yeah, this keeps biting us on the rump too.

**Comment by emilk** [comment]
Its very easy to write `log::error!("An error occurred: {err}")` and then get a user report three months later and only then realize you are missing the most important part(s) of the error message.

Does anyone know any good way of preventing this problem? e.g. some way to make clippy warn me when using `Display` on `anyhow::Error`?

**Comment by smoelius** [comment]
> Does anyone know any good way of preventing this problem? e.g. some way to make clippy warn me when using `Display` on `anyhow::Error`?

I don't think this is currently possible, though it appears many people want it: https://github.com/rust-lang/rust-clippy/issues/8581
