### ISSUE TITLE
Use non-thread safe structs as errors?

### ISSUE THREAD

**Issue by augusto2112** [dtolnay/anyhow#86]
Hi! I'm new to rust, so sorry if this is a stupid question. I'm writing a single-threaded app, and I'm using a custom struct as an error with anyhow. This was working fine until I added an `Rc<RefCell<Foo>>` field. After that, I got an error when I try to downcast the error to my type. Looking at the declarations, it seems all the `downcast` need the downcasted type to be `Send`. Since my program is single-threaded, I don't think that's needed in my case, so is there a way to downcast an error to a type which isn't thread-safe?

Thanks!

**Comment by dtolnay** [comment]
There isn't; it's extremely unusual to have Rc\<RefCell\<\>\> inside an error. Can you extract whatever you need from the Rc when the error value is constructed? The error should hold the minimum needed for rendering an informative message.
