### ISSUE TITLE
Easy way to combine errors

### ISSUE THREAD

**Issue by Moxinilian** [dtolnay/anyhow#88]
Sometimes when one is handling an error, they might need to do some fallible operations in order to "clean up" the context. However it then makes it hard to return both errors in case the fallible operation too failed.

Maybe declaring reasonable tuples of errors to be errors could work? Is there a way to handle this case already?

**Comment by dtolnay** [comment]
Closing because this isn't something that I would like to pursue in this library. The closest would probably be to collect your errors in a vector and have some logic for concatenating the error messages.

```rust
use std::fmt::{self, Display};

#[derive(Debug)]
pub struct MultiError {
    errors: Vec<anyhow::Error>,
}

impl Display for MultiError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        // ...
    }
}

impl std::error::Error for MultiError {}
```
