### ISSUE TITLE
Downcast during conversion from anyhow::Error to enum

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/anyhow#90]
*Moved from https://github.com/dtolnay/anyhow/issues/89#issuecomment-623346081.*

---

An external library I'm using returns `anyhow::Error`. Underneath it's a `io::Error`. I want to use `thiserror` to wrap this error in my own type.

Something like this works:

```rust
#[derive(Debug, Display, Error)]
pub enum MyError {
    /// missing source
    MissingSource(#[from] anyhow::Error),
}
```

But I'm trying to figure out how I can make it `#[from] std::io::Error` since `anyhow::Error` could be any type of error.

One solution I could see is downcasting the generic error and add a second `MyError::Other` type to fall back to, but is that the conventional solution here, since that seems to be a relatively verbose solution that requires me to map the errors vs just appending the `?` operator.

I'd rather have it automatically fall back to the unknown error using the technique described in `thiserror`:

```rust
#[derive(Debug, Display, Error)]
pub enum MyError {
    /// missing source
    MissingSource(#[from] std::io::Error),
    // ^ use this if `anyhow::Error` downcasts to `io::Error`

    #[error(transparent)]
    Other(#[from] anyhow::Error)
    // ^ use this if no other error matches
}
```

_Originally posted by @JeanMertz in https://github.com/dtolnay/anyhow/issues/89#issuecomment-623346081_

**Comment by dtolnay** [comment]
If you want `?` to work, the conversion needs to handle all possible types, including ones that are not std::io::Error.

Likely something like:

```rust
use thiserror::Error;

#[derive(Error, Debug)]
pub enum MyError {
    #[error("missing source")]
    MissingSource(#[from] std::io::Error),

    #[error(transparent)]
    Other(anyhow::Error),
}

impl From<anyhow::Error> for MyError {
    fn from(e: anyhow::Error) -> Self {
        match e.downcast::<std::io::Error>() {
            Ok(io) => MyError::MissingSource(io),
            Err(other) => MyError::Other(other),
        }
    }
}
```

**Comment by JeanMertz** [comment]
Thanks @dtolnay, that works great.

For anyone coming along, here's the full example which still allows you to wrap the `Unknown` variant with your own message, and makes it easier to start adding more downcasts as needed:

```rust
use thiserror::Error;

#[derive(Error, Debug)]
pub enum MyError {
    #[error("missing source")]
    MissingSource(#[from] std::io::Error),

    #[error("unknown error")]
    Unknown { source: anyhow::Error },
}

impl From<anyhow::Error> for MyError {
    fn from(err: anyhow::Error) -> Self {
        let err = match err.downcast::<std::io::Error>() {
            Ok(err) => return MyError::MissingSource(err),
            Err(err) => err,
        };

        // add more as needed...

        MyError::Unknown { source: err }
    }
}
```

**Comment by dtolnay** [comment]
Nice!
