### ISSUE TITLE
Concatentating error chains

### ISSUE THREAD

**Issue by cpick** [dtolnay/anyhow#93]
I have a program that has several mechanisms that it can use to accomplish its task; they are attempted in order from most preferred down to least.  If at least one of these mechanisms succeeds the program is happy, if they all fail I'd like to report the causes for all the failures.

A simplified version of my first attempt:
```rust
use anyhow::{bail, Context, Result};

fn primary() -> Result<()> {
    bail!("failed primary")
}

fn fallback() -> Result<()> {
    bail!("failed fallback")
}

fn main() -> Result<()> {
    primary().or_else(|error| {
        fallback()
            .context("fallback context")
            .map_err(|e| error.context(e))
    })
}
```
Reported:
```
Error: fallback context

Caused by:
    failed primary
```

This omitted the fallback error's causes (just "failed fallback" in this case, but in the real program an number of possible failures with different numbers of causes).

I didn't see any way to "append" a context chain to an Error so I attempted to do it with:
```rust
fn main() -> Result<()> {
    primary().or_else(|error| {
        fallback()
            .context("fallback context")
            .map_err(|e| e.chain().rev().fold(error, |error, e| error.context(e)))
    })
}
```
But that fails to compile with:
```
error[E0277]: `dyn std::error::Error` cannot be shared between threads safely
  --> src/main.rs:15:79
   |
15 |             .map_err(|e| e.chain().rev().fold(error, |error, e| error.context(e)))
   |                                                                               ^ `dyn std::error::Error` cannot be shared between threads safely
   |
   = help: the trait `std::marker::Sync` is not implemented for `dyn std::error::Error`
   = note: required because of the requirements on the impl of `std::marker::Send` for `&dyn std::error::Error`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```
(I didn't expect `Chain::Item` to be `!Sync` since `Context::context()` takes an argument that's `Send + Sync`, but I didn't dig too deeply so I'm probably missing the reason.)

I'm considering just "flattening" the fallback errors:
```rust
            .map_err(|e| error.context(format!("{:#}", e)))
```
But that would be a slight disappointment because the real program makes good use of the different ways to format errors (eg it prints stack traces for all the causes when debugging locally, prints the errors with `{:?}` or `{:#}` depending on the situation, etc) and it'd be a bit unfortunate to lose those details for the inner portions of the fallback failures.

I was wondering if there's any way to accomplish what I'm looking for or perhaps an entirely different strategy that I haven't thought of?  (I realize that the "primary" error is not strictly the *cause* of the "fallback" error, but in this case it is the reason the fallback was attempted and the reasons for all the failures are important if none of the mechanisms succeed.)

Thank you for such a useful crate and for any thoughts you may have!

**Comment by dtolnay** [comment]
I think the question you've asked minimizes to: how do I write a function that takes error A with cause chain A1, A2 and error B with cause chain B1, B2 and produces error C with A's message and with cause chain A1, A2, B, B1, B2. Is that right?

As far as I know the lifetimes in Error::source wouldn't allow that unless you rely on something like a thread_local to stash the second half of the cause chain at the beginning. You could construct such a function with a thread_local but it would not be great.

But separately, consider whether a concatenated cause chain is the best way to present the failure for the user's consumption. It may be that a type that aggregates a collection of errors would be better.

```rust
pub struct AltErrors {
    errors: Vec<anyhow::Error>,
}

impl Display for AltErrors {
    /* render all the errors in a way that indicates the fallback relationship */
}

impl std::error::Error for AltErrors {}
```

**Comment by dtolnay** [comment]
https://github.com/yaahc/color-eyre/blob/7b2d9f4218b90ed590163c60c0feba237113b0ec/examples/multiple_errors.rs has an example along these lines; the errors end up getting pushed to a Vec ([this one](https://github.com/yaahc/color-eyre/blob/7b2d9f4218b90ed590163c60c0feba237113b0ec/src/lib.rs#L296)) and then rendered one after another ([here](https://github.com/yaahc/color-eyre/blob/7b2d9f4218b90ed590163c60c0feba237113b0ec/src/lib.rs#L449-L455)).

**Comment by cpick** [comment]
> I think the question you've asked minimizes to: how do I write a function that takes error A with cause chain A1, A2 and error B with cause chain B1, B2 and produces error C with A's message and with cause chain A1, A2, B, B1, B2. Is that right?

Yes, exactly.

> As far as I know the lifetimes in Error::source wouldn't allow that unless you rely on something like a thread_local to stash the second half of the cause chain at the beginning. You could construct such a function with a thread_local but it would not be great.

Hmm, I hadn't even considered lifetime issues. 

> But separately, consider whether a concatenated cause chain is the best way to present the failure for the user's consumption. It may be that a type that aggregates a collection of errors would be better.

Definitely not ideal.  If it could be made to work it may be "good enough", but since it already doesn't then doing the bit of extra work to get it right (following your `AltErrors` suggestion or the color-eyre example) seems like the right idea.

Thank you for the guidance, I'm always blown away by the rust community!
