### ISSUE TITLE
collect() to Result<Vec<_>, anyhow::Error>

### ISSUE THREAD

**Issue by sid-6581** [dtolnay/anyhow#95]
I'm not sure if this is a supported scenario, but if I a have e.g. a `Vec<Result<_, io::Error>>` and I try to use `collect()` to get it into a `Result<Vec<_>, anyhow::Error>` I get this error:

>a value of type `std::result::Result<std::vec::Vec<std::path::PathBuf>, anyhow::Error>` cannot be built from an iterator over elements of type `std::result::Result<std::path::PathBuf, std::io::Error>`

Everything works if I explicitly map the error using `Error::new` before `collect()`, but I was hoping I could avoid that. I didn't see any mention of iterators of errors in the documentation or any examples, so I'm not sure if this is by design or if I'm overlooking something.

**Comment by dtolnay** [comment]
This is up to Result's trait impls in the standard library. It requires that the iterator's error type and the output error type are the same. https://github.com/rust-lang/rust/blob/1.43.0/src/libcore/result.rs#L1455

Either of these should work:

```rust
iter.collect::<Result<Vec<_>, _>>()
    .map_err(anyhow::Error::new)
```

```rust
iter.map(|res| res.map_err(anyhow::Error::new))
    .collect::<Result<Vec<_>, _>>()
```
