### ISSUE TITLE
Provide backtrace on stable

### ISSUE THREAD

**Issue by Riateche** [dtolnay/anyhow#98]
It seems that now anyhow errors contain no backtraces on stable, making it very hard to find error location unless you pass contexts manually. Can we use `backtrace` crate to provide backtraces on stable?

**Comment by dtolnay** [comment]
Hi @Riateche, standard library backtraces are close to stabilizing (https://github.com/rust-lang/rust/pull/72981) so I would prefer not to make a change right now.

**Comment by theduke** [comment]
@dtolnay it seems that backtrace stabilization is on hold, with unresolved API design questions.

Would you be open to reconsidering?

**Comment by yuriks** [comment]
Another thing that could be done is use [`Location::caller`](https://doc.rust-lang.org/std/panic/struct.Location.html) and `#[track_caller]` to at least get information about the line where intermediate `.context` call (or other anyhow conversions) were done. This is stable today and wouldn't require extra dependencies.

**Comment by stevenroose** [comment]
Yeah losing stacktraces is quite annoying. We were considering moving from have our internal programs just use `panic!` and `.expect` everywhere to use anyhow with more digestible contexts.

But losing the backtrace is really sad. And "just waiting" is quite annoying too. Wouldn't it make sense to have an implementation based on the `backtrace` crate that's in an experimental feature that explicitly says that the API might break when std::backtraces lands? AFAIK the API will be very similar, so most of the implementation will be able to be retained.

**Comment by MightyPork** [comment]
std Backtrace is now put on hold, again: https://github.com/rust-lang/rust/pull/72981#issuecomment-768625372
This can take years, without exaggerating. Couldn't the backtrace crate be used in place of std backtrace using `#[cfg(backtrace-crate)]` or such?
